- doc/rules-reference.md
- src/extract/extract.js
- src/extract/gatherInitialSources.js
- src/extract/index.js
- src/extract/jsonschema.json
- src/extract/resolve/determineDependencyTypes.js
- src/validate/jsonschema.json
- test/extract/extract-composite.spec.js
- test/extract/extract.spec.js
- test/extract/fixtures/bundled-dependencies.json
- test/extract/fixtures/bundled-dependencies/index.js
- test/extract/fixtures/bundled-dependencies/node_modules/idontgetbundled/index.js
- test/extract/fixtures/bundled-dependencies/node_modules/idontgetbundled/package.json
- test/extract/fixtures/bundled-dependencies/node_modules/igetbundled/index.js
- test/extract/fixtures/bundled-dependencies/node_modules/igetbundled/package.json
- test/extract/fixtures/bundled-dependencies/package.json
- see https://docs.npmjs.com/files/package.json#bundleddependencies
- introduces a new 'npm-bundled' dependency type, that can come on top of other dependency types.
- the dependency type can be present in the output format and can be used in the rule spec
- prerequisite for properly testing bundled dependencies
- extract has a pOptions.baseDir parameter that allows callers to specify a base dir.
- this base dir was respected in some places, not in others - resulting in errors
- we haven't bumped into this in production because
- the cli doesn't expose it yet
- no consumer yet uses the feature
- So why fix it now?
- It's convenient when testing - testing bundled dependencies would be hard without it (would e.g. require to have dependency-cruiser's own package.json include a bundled …
> recognize bundled dependencies

- npm-shrinkwrap.json
- package.json
- src/extract/transpile/meta.js
- test/extract/transpile/meta.spec.js
- test/main/fixtures/tsx.json
- test/main/fixtures/tsx/index.ts
- test/main/fixtures/tsx/sub/render.tsx
- test/main/main.spec.js
Adds support for .tsx
- dependency-cruiser currently doesn't supports .tsx (as signaled in #10 by @kyo-ago => thanks!)
- it should (high value)
- it's easy to add (low effort)
low effort * high value = high priority
Yep - added unit tests
- tsc already supports tsx out of the box, so adding the .tsx extension to `meta.js` solves the issue
- the rest of the commits are
- tests to prove this stuff works as intended
- version upgrades of some of the dependencies that weren't on _latest_ yet (<= should've been done on develop first and merged on here later but 🤷‍♂️ )
> Add support for tsx

- src/extract/transpile/jsxImplementationRationale.md
- src/extract/transpile/meta.js
- test/extract/transpile/fixtures/jsx.js
- test/extract/transpile/fixtures/jsx.jsx
- test/extract/transpile/jsxWrap.spec.js
- test/extract/transpile/meta.spec.js
- test/main/fixtures/jsx.json
- test/main/fixtures/jsx/index.js
- test/main/fixtures/jsx/jsx.jsx
- test/main/main.spec.js
- adds support for .jsx
- uses acorn_loose for parsing. This might seem a strange choice - see _alternatives_ for reasons
- For this I introduced jsx as a new alt-js language - with babel-core as the transpiler. 
- babel-core needs plugins to be able to do anything. For react there is:
- `babel-plugin-transform-react-jsx` - this should suffice for purely jsx additions to no-frills javascript (sorta es3). Most react projects uses fancier javascript (es6 or better, with classes, proper module support etc), so without the plugins supporting those the transpilation would fail.
- `babel-preset-react` - this is a collection of plugins. It contains transform-react-jsx, and some nice stuff for typical react projects (a.o. es6+ support). 
- The philosophy of dependency-cruiser is to use the …
> Add jsx support

- src/cli/normalizeOptions.js
- src/cli/validateParameters.js
- src/extract/extract.js
- src/extract/index.js
- src/extract/resolve/index.js
- src/extract/resolve/resolve-AMD.js
In some cases the code used lodash where out of the box javascript would've done just as well (_.isArray, _.isString, _.defaults, _.sort _.uniq). This cleans that up so these spots are easier to maintain.
Non-regression with the unit tests.
- ~~~New feature (non-breaking change which adds functionality)~~~
- ~~~Breaking change (fix or feature that would cause existing functionality to change)~~~
- ~~~My change requires a change to the documentation.~~~
- ~~~I have updated the documentation accordingly.~~~
> Replace lodash with native variants

- src/cli/normalizeOptions.js
- test/cli/normalizeOptions.spec.js
--module-systems "cjs, amd, es6" used to complain about module systems not being invalid. We now just strip the spaces
unit test
- ~~~[ ] New feature (non-breaking change which adds functionality)~~~
- ~~~[ ] Breaking change (fix or feature that would cause existing functionality to change)~~~
- ~~~[ ] My change requires a change to the documentation.~~~
- ~~~[ ] I have updated the documentation accordingly.~~~
> bugfix(cli): trims spaces from passed module systems

- bin/dependency-cruise
- doc/api.md
- doc/cli.md
- doc/rules-reference.md
- package.json
- src/extract/extract.js
- src/extract/index.js
- src/extract/jsonschema.json
- src/extract/resolve/index.js
- src/main/index.js
- src/main/options/defaults.json
- src/main/options/validate.js
- src/main/ruleSet/jsonschema.json
- test/cli/fixtures/cjs.dir.filtered.json
- test/cli/fixtures/cjs.dir.json
- test/cli/fixtures/cjs.file.json
- test/cli/fixtures/multiple-in-one-go.json
- test/extract/extract.spec.js
- test/extract/fixtures/amd.json
- test/extract/fixtures/amd/symlink.js
- test/extract/fixtures/cjs.json
- test/extract/fixtures/cjs/symlink.js
- test/main/fixtures/jsx.json
- test/main/fixtures/ts.json
- test/main/fixtures/tsx.json
- test/main/options/validate.spec.js
- types/dependency-cruiser.d.ts
Add option `preserveSymlinks` everywhere:
* resolve/index.js
* works for both AMD and CJS
* extract.js
* validate.js
* defaults.json
* jsonschema (twice, don't know why)
* CLI
* docs
* tests
The option (currently) defaults to `true` which leaves the old behavior unchanged. This can and probably should be changed in a future major version to be consistent with Node's default behavior.
To disable this option, either specify it in the config file or use the CLI argument `--preserve-symlinks false`.
Fixes: #33 
Tested in the unit tests. (needed to add a devDependency on `symlink-dir` for easier handling of symlinks on windows)
Also tested locally with in my project https://github.com/fimbullinter/wotan. Tested config file and CLI option.
- ~~[ ] Bug fix (non-breaking change which fixes an …
> Add option to preserve/resolve symlinks

- doc/rules-reference.md
This wasn't clear to me, when I run `depcruise --validate .dependency-cruiser.json src`, exactly what I was trying to match in that regex. (relative to here? relative to src? relative to the file, as passed to `import` ?)
Thank you for making this tool and publishing and documenting it! This was really useful yesterday in identifying a circular dependency in TypeScript, which mocha totally barfs on.
> Plan to do something drastic?     
> Leave an [issue](https://github.com/sverweij/dependency-cruiser/issues/new) with a
> do that.
> specify which path we're matching

- README.md
- doc/faq.md
- src/extract/transpile/jsxImplementationRationale.md
- src/extract/transpile/meta.js
- test/extract/fixtures/vue.json
- test/extract/fixtures/vue/App.vue
- test/extract/fixtures/vue/components/HelloWorld.vue
- test/extract/fixtures/vue/main.js
- test/extract/index.spec.js
- test/extract/transpile/fixtures/vue.js
- test/extract/transpile/fixtures/vue.vue
- test/extract/transpile/javascriptWrap.spec.js
- test/extract/transpile/meta.spec.js
Adds support simple/ naive support for vuejs' `.vue` templates.
> feature(transpile): support for vue templates

- doc/rules-reference.md
- package.json
- src/extract/jsonschema.json
- src/extract/resolve/determineDependencyTypes.js
- src/extract/resolve/resolve-commonJS.js
- src/main/ruleSet/jsonschema.json
- test/extract/resolve/determineDependencyTypes.spec.js
- types/dependency-cruiser.d.ts
- Introduces the `localmodule` `dependencyType` for modules that are in the (webpack type) `resolve.modules` array, but which are not `node_modules`
This solves issue #51 and it enables distinguisinging local dependencies and local dependencies in the resolve module array.
fixes #51 
- unit tests
- ~~~Breaking change (fix or feature that would cause existing functionality to change)~~~
> Introduce 'localmodule' dependency type

- doc/cli.md
- doc/rules-reference.md
- src/cli/index.js
- src/cli/normalizeOptions.js
- src/extract/extract.js
- src/extract/jsonschema.json
- src/main/ruleSet/jsonschema.json
- test/cli/fixtures/rules.tsConfigNoFileName.json
- test/cli/fixtures/rules.webpackConfigNoFileName.json
- test/cli/normalizeOptions.spec.js
- test/main/ruleSet/normalize.spec.js
Adds the `--ts-config` command line option as a .dependency-cruiser.json `option`.
- to remain consistent how webpack.config.js is handled,
- to declutter command line typing each time
> Feature: allow tsconfig spec in dependency cruiser.json

- .dependency-cruiser-custom.json
- src/cli/initRules.js
- src/cli/normalizeOptions.js
- src/cli/rules.starter.json
- test/cli/fixtures/rules.withcomments.json
- test/cli/initRules.spec.js
- test/cli/normalizeOptions.spec.js
- allow comments in .dependency-cruiser.json config files
- 🐶 🥘 : add comments to dependency-cruiser's own rule file
- add comments to the rule file created with --init
I've found comments in e.g. typescript and eslint configs to be very helpful. Assuming it'd be useful for dependency-cruiser users as well & given Implementing it is a doddle => let's add it.
> feature(cli): allow comments in .dependency-cruiser.json config files

- bin/dependency-cruise
- package.json
- src/cli/index.js
- src/cli/io.js
- test/cli/fixtures/rules.sub-not-allowed-error.json
- test/cli/index.spec.js
Set the exit code to 1 if an exception occurs, instead of keeping it on 0.
Currently, if an exception occurs (e.g. config file not found, can't write to output, error in the config file, ...) dependency-cruiser happily returns 0 as the exit code - it just outputs the error message on stderr. This means it's easier for those exceptions like that to remain undetected - e.g. running on your ci, or as part of a build script, both of which expect non-zero exit codes when something is wrong.
This PR corrects that, so that if something is amiss with running dependency-cruiser it's obvious immediately.
This PR also
- makes sure cli error messages get written to stderr in less spots
- refactors the process exiting so it's unit testable
> bugfix(cli): if an exception occurs, return 1 as an exit code

- src/extract/transpile/meta.js
- test/extract/transpile/fixtures/mjs.js
- test/extract/transpile/fixtures/mjs.mjs
- test/extract/transpile/javascriptWrap.spec.js
- test/extract/transpile/meta.spec.js
Even though node's es6 module support is expiremental (`--experimental-modules`) - dependency-cruiser should support it.
- ~~~[ ] My change requires a change to the documentation.~~~
- ~~~[ ] I have updated the documentation accordingly.~~~
> feature(transpile): support mjs

- package.json
- src/cli/index.js
- test/cli/index.spec.js
- The `err` reporter (which is meant for running as part of scripts or on the ci) returns non-zero exit codes when there's > 1 error level transgression found
- Before this fix other reports did this as well, which makes e.g. running an `npm run depcruise:graph` error, while it definitely should not.
- After this fix `err` again is the only reporter doing this
> bugfix(cli): don't return a nonzero exit code when there's transgressions and the reporter !== 'err'

- package.json
- src/cli/utl/io.js
so node doesn't get seduced to use something different (e.g. apparantly on win10 UTF16-blah?
addresses #76
> bugfix(cli): specify utf8 charset when writing to stdout

- doc/rules-reference.md
- package.json
- src/extract/jsonschema.json
- src/main/ruleSet/jsonschema.json
- src/main/ruleSet/normalize.js
- test/main/ruleSet/normalize.spec.js
- test/main/ruleSet/validate.spec.js
- types/dependency-cruiser.d.ts
When extending a rule set, you might need or want to ignore some of the rules - e.g. because it's not applicable in the current situation. To enable this the `severity` of _forbidden_ rules and the `allowedSeverity` for _allowed_ rules can now have the value `ignore` - in which case dependency-cruiser disregards them completely.
> feature(rules): adds the 'ignore' severity level

- src/cli/initConfig/createConfigFile.js
- src/cli/initConfig/getUserInput.js
- src/cli/initConfig/helpers.js
Adds two questions to the `--init` script that
- get asked when there's a tsconfig or webpack config respectively
- add a tsconfig and/ or webpack config to the .dependency-cruiser-config
- makes enrolment easier
- either config needs to be specified in order to be taken into account - this might not be apparent from the documentation
> feature(cli): add simple tsconfig and webpack config detection to --init

- doc/cli.md
- docs/dependency-cruiser-dependency-graph.html
- package.json
- src/report/dot/moduleLevel/index.js
- test/report/dot/moduleLevel/index.spec.js
- test/report/fixtures/prefix-non-uri.dot
- test/report/fixtures/prefix-non-uri.json
- test/report/fixtures/prefix-uri.dot
- test/report/fixtures/prefix-uri.json
Prefixes in links in the dot output get `path.posix.join`ed to the source path. That works fine for regular file prefixes, but doesn't for uri's; `path.join` transforms `https://www.aapnootmies.org` to `https:/www.aapnootmies.org`.
To resolve that:
- uri like prefixes just get concatenated
- all others retain the existing treatment
> bugfix(dot): output correct url's, also when the prefix is an uri

- src/extract/ast-extractors/extract-typescript-deps.js
- src/extract/extract.js
- test/extract/ast-extractors/extract-typescript-commonjs.spec.js
- test/extract/fixtures/ts-recursive.json
- test/extract/fixtures/ts.json
- test/extract/fixtures/ts/index.ts
- test/main/fixtures/ts-no-precomp-cjs.json
- test/main/fixtures/ts-no-precomp-es.json
- test/main/fixtures/ts-precomp-cjs.json
- test/main/fixtures/ts-precomp-es.json
- test/main/fixtures/ts-precompilation-deps-off-cjs/also-used.ts
- test/main/fixtures/ts-precompilation-deps-off-cjs/definitely-used.ts
- test/main/fixtures/ts-precompilation-deps-off-cjs/imported-from-index-but-not-used.ts
- test/main/fixtures/ts-precompilation-deps-off-cjs/index.ts
- test/main/fixtures/ts-precompilation-deps-off-es/also-used.ts
- test/main/fixtures/ts-precompilation-deps-off-es/definitely-used.ts
- test/main/fixtures/ts-precompilation-deps-off-es/imported-from-index-but-not-used.ts
- test/main/fixtures/ts-precompilation-deps-off-es/index.ts
- test/main/fixtures/ts-precompilation-deps-on-cjs/also-used.ts
- test/main/fixtures/ts-precompilation-deps-on-cjs/definitely-used.ts
- test/main/fixtures/ts-precompilation-deps-on-cjs/imported-from-index-but-not-used.ts
- test/main/fixtures/ts-precompilation-deps-on-cjs/index.ts
- test/main/fixtures/ts-precompilation-deps-on-es/also-used.ts
- test/main/fixtures/ts-precompilation-deps-on-es/definitely-used.ts
- test/main/fixtures/ts-precompilation-deps-on-es/imported-from-index-but-not-used.ts
- test/main/fixtures/ts-precompilation-deps-on-es/index.ts
- test/main/fixtures/tsconfig.targetcjs.json
- test/main/fixtures/tsconfig.targetes.json
- test/main/main.spec.js
- Adds extraction of commonJS dependencies to the typescript extractor
- The extraction function now either uses the typescript AST or the javascript one, making things possibly faster, but also fixing issues like #111
> fix(extract): parse and analyze only once

- src/main/index.js
- src/main/resolveOptions/normalize.js
- test/extract/resolve/index.spec.js
- test/main/resolveOptions/normalize.spec.js
See title
This should prevent some confusion - the ts paths plugin will complain at runtime it doesn't want to load the tsconfig if there's no baseUrl. This runtime message looks like it's coming from dependency-cruiser, while it isn't. Actually everything is fine; just the paths resolution isn't done with the paths plugin (which is ok - there was no baseUrl and likely no pathsin the tsconfig in the first place).
Solution: just don't load the ts paths plugin when there's no baseUrl in the tsconfig.
> feature(main): only load the ts paths plugin when the tsconfig contains a baseUrl

- doc/faq.md
- src/main/index.js
- src/report/csv/index.js
- src/report/dot/folderLevel/index.js
- src/report/dot/moduleLevel/index.js
- src/report/err.js
- src/report/html/index.js
- src/report/json.js
- test/report/dot/folderLevel/index.spec.js
- test/report/dot/moduleLevel/index.spec.js
- test/report/dot/moduleLevel/rcdot.spec.js
- test/report/err.spec.js
- test/report/html.spec.js
Reporters now take a dependency list object and return their output. Previously they wrapped it in the 'modules' section of the 
The 'hack' to wrap the output in the modules section is there for a specific case in the cli. The hack itself is not necessary but removing it will constitute a breaking change to the cruise API. Removing that hack will be done in the future - this PR is groundwork for that. Side effects are that it makes writing reporters easier and that it enables the use of a different composition pattern if necessary.
> refactor(report): simplify the reporter contract

- doc/faq.md
- src/extract/ast-extractors/estree-utl.js
- src/extract/ast-extractors/extract-ES6-deps.js
- src/extract/ast-extractors/extract-commonJS-deps.js
- src/extract/ast-extractors/extract-typescript-deps.js
- test/extract/ast-extractors/extract-ES6-deps.spec.js
- test/extract/ast-extractors/extract-commonjs-deps.spec.js
- test/extract/ast-extractors/extract-typescript-commonjs.spec.js
- test/extract/ast-extractors/extract-typescript-dynamic-imports.spec.js
- test/extract/ast-extractors/extract-typescript-imports.spec.js
Additionally recognizes dynamic imports (and commons requires) that have a placeholder-less template literal as a parameter
```typescript
import(`circular`).then(pBla => circular.makeAngular(8));
const th_ = require(`thunderscore`);
const lala : import(`types`).T;
```
Covers:
- typescript (both `import` statements and `require` calls)
- typescript _type imports_
- javascript (both `import` statements and `require` calls)
- (coffee and live script if they compile down to either of the javascript equivalents) 
Although it might not make a whole lot of sense to use a template literal instead of a regular string, it is legal. In [Angular 8.0's release notes](https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27) it's used as an …
> feature(extract): recognize dynamic imports with template literals (that contain no placeholders)

- src/report/err.js
- src/report/teamcity.js
- test/report/err.spec.js
- test/report/fixtures/one-violation.json
- test/report/fixtures/teamcity/module-errors-teamcity-format.txt
- Enhances readability in said reporters.
- Conceptually closer to the nature of the violation
E.g. in the _err_ reporter observe the no-orphans violation:
Before:
```
warn cli-to-main-only-warn: src/cli/compileConfig/index.js → src/extract/resolve/resolve.js
error no-orphans: src/tmp_orphan.js → src/tmp_orphan.js
✖ 2 dependency violations (1 errors, 1 warnings). 201 modules cruised.
```
After:
```
warn cli-to-main-only-warn: src/cli/compileConfig/index.js → src/extract/resolve/resolve.js
error no-orphans: src/tmp_orphan.js
✖ 2 dependency violations (1 errors, 1 warnings). 201 modules cruised.
```
- ~~My change requires a change to the documentation.~~
- ~~I have updated the documentation accordingly.~~
> feature(report): err, teamcity: only emit the module name once for module-only rule violations

- src/extract/derive/orphan/index.js
- src/validate/matchModuleRule.js
- test/extract/derive/orphan/fixtures/twoModule.afterprocessing.json
- test/extract/derive/orphan/index.spec.js
Also make orphan checks work in 'allowed' and make sure that if you _do_ want orphans somewhere for some reason, you specify that as part of a rule as well now.
(despite 100% test coverage there's some additional tests that can be done to prevent regression - those will be added in PR #142, which also refactors the test set up of the validation functions.
> bugfix(orphan): also make orphan checks work in 'allowed'

- src/extract/results-schema.json
- src/extract/summarize.js
- src/extract/utl/order.js
- test/cli/fixtures/cjs.dir.filtered.json
- test/cli/fixtures/cjs.dir.json
- test/cli/fixtures/cjs.dir.stdout.json
- test/cli/fixtures/cjs.file.json
- test/cli/fixtures/dynamic-import-nok.json
- test/cli/fixtures/dynamic-import-ok.json
- test/cli/fixtures/multiple-in-one-go.json
- test/cli/fixtures/typescript-path-resolution.json
- test/cli/fixtures/webpack-config-alias-cruiser-config.json
- test/cli/fixtures/webpack-config-alias.json
- test/extract/fixtures/cache-busting-first-tree.json
- test/extract/fixtures/cache-busting-second-tree.json
- test/extract/summarize.spec.js
- test/extract/utl/order.severities.spec.js
- test/extract/utl/order.violations.spec.js
- test/main/fixtures/dynamic-imports/es/output.json
- test/main/fixtures/dynamic-imports/typescript/output-pre-compilation-deps.json
- test/main/fixtures/dynamic-imports/typescript/output.json
- test/main/fixtures/jsx-as-object.json
- test/main/fixtures/jsx.json
- test/main/fixtures/ts-no-precomp-cjs.json
- test/main/fixtures/ts-no-precomp-es.json
- test/main/fixtures/ts-precomp-cjs.json
- test/main/fixtures/ts-precomp-es.json
- test/main/fixtures/ts.json
- test/main/fixtures/tsx.json
- Emits violations in order of severity, rule name, from, to - instead of just looking to the from and too.
- Also adds a 'dependenciesCruised' attribute - so you can see how many were cruised.
This makes reports that focus on errors easier to read & act upon. Especially on projects with thousands of modules & dependencies, the number of violations might be so big that a sort order makes a world of a difference. 
Currently affects the `err` reporter - but in the upcoming html err reporter it will be more useful even.
> feature(extract): more actionable default violation ordering

- src/main/resolveOptions/normalize.js
- test/main/fixtures/type-only-module-references/node_modules/@types/graphql/package.json
- test/main/fixtures/type-only-module-references/node_modules/@types/graphql/tsutils/Maybe.d.ts
- test/main/fixtures/type-only-module-references/output-no-ts.json
- test/main/fixtures/type-only-module-references/output.json
- test/main/fixtures/type-only-module-references/src/use-maybe.ts
- test/main/main.type-only-module-references.spec.js
- test/main/resolveOptions/normalize.spec.js
- adds node_modules/@types as a spot to look for external modules
- In typescript projects you sometimes use stuff that _only_ occurs in a node_modules/@types - e.g. the `graphql/tsutils/Maybe` type definition.
We want dependency-cruiser to find these as well when cruising for ts-pre-compilation dependencies.
> bugfix(resolve): also resolve modules that only occur in node_modules/@types

- src/main/options/validate.js
- test/main/options/validate.spec.js
- The maxDepth option is a number, but was processed as a string (because --max-depth is a string), giving errors. 
Due to this bug maxDepth in a config didn't work at all.
> bugfix(options): correctly process maxDepth specified in configs

- src/validate/matchDependencyRule.js
- src/validate/matches.js
- test/validate/matches.spec.js
When using group matching expressions, only the first `$` parameter was replaced, which made that a rule like this would not be matched correctly.
```javascript
module.exports = {
forbidden: [
{
from: {
path: "^src(/.+)/[^/]+$",
},
to: {
pathNot: "src/$1/okidoki|lib/$1",
}
}
]
}
```
With this PR the second `$1` in the `pathNot` will be heeded correctly as well.
- ~~My change requires a change to the documentation.~~
- ~~I have updated the documentation accordingly.~~
> bugfix(validate): make group matching more complete

- bin/dependency-cruise
- doc/cli.md
Betterizes comprehensibility of the cli. Also warns about the removal of the _rcdot_ type in 5.0.0 - which has been deprecated a while ago.
> doc(cli): bring --help output up to date

- src/extract/extract.js
- src/extract/index.js
- src/extract/parse/toTypescriptAST.js
- test/extract/fixtures/es6.json
- test/extract/fixtures/es6/imports-and-exports.js
replaces the two spots that still imported lodash wholesale (for chaining) with imports of lodash individual functions.
- More clear what's used
- Easier to reduce download size (we're not using everything in lodash).
That last one doesn't materialise, though, because it's used as a transient dependency (by inquirer)
> refactor(extract): only use individual lodash functions

- src/extract/resolve/determineDependencyTypes.js
- src/extract/resolve/index.js
- src/extract/resolve/isRelativeModuleName.js
- src/extract/resolve/localNpmHelpers.js
- test/extract/resolve/isRelativeModuleName.spec.js
- sort `.thing.js` into the external module bin instead of the local one
- centralises the function that determines this
`./hello` is local, but `.hello` is not, despite starting with a dot. It requires `./.hello` to make it that. The resolver now correctly identifies them.
It's an edge case (npm discourages the use of package names starting with a .), but it should be handled correctly.
> bugfix(resolve): in edge cases correctly determine relativeness as well

- package.json
- src/extract/resolve/isCore.js
- test/extract/resolve/isCore.spec.js
use resolve.isCore instead of core functionality to detect the whether a module is core as some (still) supported node versions (elder 8 and 6 - newer 8 and 6 _do_ have it!) donot have this functionality in the `module` module - as discovered in #167.
Reverts #170 that started to use the `module` module for this functionality
> bugfix(resolve): use resolve.isCore instead of core functionality for the same

- doc/cli.md
- src/main/index.js
- src/main/options/validate.js
- src/report/index.js
- See title (BREAKING CHANGE)
- The rcdot alias was deprecated for a few minor versions already because it was superfluous
> refactor(report): remove the 'rcdot' alias for the dot reporter

- bin/dependency-cruise
- src/cli/validateNodeEnv.js
- test/cli/valideNodeEnv.spec.js
extracts the platform check into a separate function so it can be re-used and unit tested. Also makes sure the cli emits a neat warning message on node 4 and 6 and doesn't show a stack trace because one of dc's dependencies uses an unsupported feature.
> refactor(cli): extracts the platform check into a separate function

- package.json
- src/extract/ast-extractors/estree-helpers.js
- src/extract/ast-extractors/extract-AMD-deps.js
- src/extract/ast-extractors/extract-ES6-deps.js
- src/extract/ast-extractors/extract-commonJS-deps.js
- src/extract/ast-extractors/walk.js
- src/extract/parse/toJavascriptAST.js
see title
... as acorn started supporting that in version 7.0.0 (as per https://github.com/acornjs/acorn/pull/844), so it's not necessary anymore to use a plugin for this. Moreover, the plugin expects acorn ^6 as a peer, and as we're using 7 npm complains about it on install, which looks daft.
> refactor(extract): use acorn instead of acorn-dynamic-import for detecting dynamic imports

- .github/workflows/nodejs.yml
- .gitlab-ci.yml
- .travis.yml
- appveyor.yml
- package.json
Enables node 13 and makes sure it's validated on the ci's (except Appveyor, which doesn't have node 13 yet). Also fixes #207.
- [/] My change requires a change to the documentation.
- [/] I have updated the documentation accordingly.
> chore(*): enable node 13

- .github/workflows/lint-test-workflow.yml
- .github/workflows/yarn-integration-workflow.yml
- test/cli/compileConfig/index.spec.js
- test/cli/getResolveConfig.spec.js
- test/cli/parseTSConfig.spec.js
- test/cli/utl/io.spec.js
- test/cli/utl/validateFileExistence.spec.js
- test/cli/valideNodeEnv.spec.js
- test/extract/extract.spec.js
- test/extract/resolve/isRelativeModuleName.spec.js
- test/extract/resolve/readPackageDeps/index.spec.js
- test/main/main.format.spec.js
- test/main/options/validate.spec.js
- test/main/ruleSet/validate.spec.js
Once in a while the test borks because there's something afoot with a temp file that's created half way. The tests themselves are successful, but something gets thrown and mocha gets in a tizzy declaring one of the tests failed and hence the suite.
Research so far:
- cli/utl/io creates a temp file in its set up and throws it away in its tear down
- to make sure the file doesn't exist yet, in the set up it's first deleted - with a try/catch to muffle any protests
- in some cases an exception related to this is thrown during the tests - popping up in random places where chai is doing a .to.throw or .to.not.throw - failing random tests
Done:
> Although they might address other imperfections in the test code, 
> some of these are probably waving a dead chicken against the problem at hand.
- …
> fix(test): make the cli/utl/io test run with more certainty

- .github/workflows/lint-test-workflow-windows-only.yml
- .github/workflows/lint-test-workflow.yml
- see title
- also splits off a separate workflow for windows (as they're slow and fail more often - that way they can be re-run independently)
- makes builds faster
By making this PR
> ci(gh-actions): set up node modules cache

- doc/faq.md
- doc/rules-reference.md
- src/cli/initConfig/config.js.template.hbs
- src/cli/initConfig/config.js.template.js
- src/cli/initConfig/config.json.template.hbs
- src/cli/initConfig/config.json.template.js
- src/extract/ast-extractors/estree-helpers.js
- src/extract/ast-extractors/extract-AMD-deps.js
- src/extract/ast-extractors/extract-commonJS-deps.js
- src/extract/ast-extractors/extract-typescript-deps.js
- src/extract/extract.js
- src/extract/results-schema.json
- src/main/options/defaults.json
- src/main/options/normalize.js
- src/main/ruleSet/config-schema.json
- test/extract/ast-extractors/extract-amd-deps.spec.js
- test/extract/ast-extractors/extract-commonjs-deps.spec.js
- test/extract/ast-extractors/extract-typescript-exotics.spec.js
- test/extract/ast-extractors/extract-typescript-others.spec.js
- test/extract/ast-extractors/extract-typescript.utl.js
- types/cruise-options.d.ts
- Adds an `exoticRequireStrings` option to the dependency-cruiser config, that takes zero or more alternative strings dependency-cruiser should treat like a function that requires other modules (see the added rules documentation for details).
- Added (commented) to the init templates
- Document in the rules reference and the FAQ
- Works for all supported languages
- Currently limited to single functions (`need('exodash')`, not yet nested ones (`window.require('elektrodash'`)
- [/] make it possible to define rules on exotic require strings (either forbidding or allowing things based on the require string used) => separate PR
- [/] implement in the typescript extraction for composites ('window.require') => separate PR
- [/] implement in the javscript extraction for composites …
> feature(extract): enable detection of commonjs dependencies not (directly) declared with 'require'

- .dependency-cruiser.json
- doc/faq.md
- package.json
- src/extract/ast-extractors/estree-helpers.js
- src/extract/ast-extractors/extract-commonJS-deps.js
- src/extract/ast-extractors/extract-typescript-deps.js
- test/extract/ast-extractors/extract-commonjs-deps.spec.js
- test/extract/ast-extractors/extract-typescript-exotics.spec.js
- Same as #216, but for composite requires (one level deep) like `window.require`
- fixes #206
> feature(extract): recognize composite exotic requires (e.g. window.require)

- .codeclimate.yml
We're using newer versions of plugins locally - so cc starts complaining it can't find some of the newer rules. Upping to aslint 6 should fix that.
> ci(codeclimate): up eslint version to use over there

- .codeclimate.yml
The eslint ecosystem moves faster than what codeclimate can keep upt with - and we're running eslint on other ci platforms anyway now.
> ci(codeclimate): remove eslint plugin from codeclimate config

- doc/rules-reference.md
`to.dynamic` should be a boolean.
The [rules reference documentation](doc/rules-reference.md ) is not in line with the [schema definition](https://github.com/sverweij/dependency-cruiser/blob/53853d3edd5c1fc0fa91f5c888198123fd6b000c/src/schema/configuration.schema.json#L164).
1) Create `.dependency-cruiser.json`
```javascript
{
"forbidden": [
{
"name": "no-non-dynamic-dependencies",
"severity": "error",
"from": {},
"to": { "dynamic": "true" }
}
]
}
```
2) Run `depcruise --validate .dependency-cruiser.json src`
3) Results in an error:
```
ERROR: The rules file is not valid: data.forbidden[0].to.dynamic should be boolean, data.forbidden[0].to 
should NOT have additional properties, data.forbidden[0] should match exactly one schema in oneOf.
```
> bugfix(doc): to.dynamic is a boolean

- doc/rules-reference.md
Path should be ../src/report/dot/defaultTheme.json (wihtout unexisting folder **common**)
Full link to file is https://github.com/sverweij/dependency-cruiser/blob/develop/src/report/dot/defaultTheme.json
> bugfix(doc): correct link to defaultTheme.json

- src/main/resolveOptions/normalize.js
- test/extract/resolve/fixtures/ts-config-with-path-correct-resolution-prio/src/aliassed/dts-before-ts.d.ts
- test/extract/resolve/fixtures/ts-config-with-path-correct-resolution-prio/src/aliassed/dts-before-ts.ts
- test/extract/resolve/fixtures/ts-config-with-path-correct-resolution-prio/src/aliassed/js-before-ts.js
- test/extract/resolve/fixtures/ts-config-with-path-correct-resolution-prio/src/aliassed/js-before-ts.ts
- test/extract/resolve/fixtures/ts-config-with-path-correct-resolution-prio/tsconfig.json
- test/extract/resolve/fixtures/ts-config-with-path/tsconfig.json
- test/extract/resolve/index.spec.js
In one of our projects we use `.d.ts` files which are not generated to limit the possibility in the file. Most of them are model files
> Leave an [issue](https://github.com/sverweij/dependency-cruiser/issues/new) with a
> do that.
Just add `.d.ts` the default is to only have `.ts` and `.tsx`. Unsure if this is the correct place though.
In one of our projects we use `.d.ts` files which are not generated to limit the possibility in the file. Most of them are model files
Tested locally on the project
> add .d.ts to allow for custom tsconfig resolving

- docs/dependency-cruiser-dependency-graph.html
- package.json
- src/extract/resolve/isFollowable.js
- src/main/resolveOptions/normalize.js
- test/extract/resolve/index.spec.js
Use the same `extensions` array as passed to `enhanced-resolve` for the ts config alias/ path plugin (instead of a hard-coded list).
Using the extensions passed to the webpack config/ the extensions dc supports with current settings makes for more flexibility (just pass it once in the webpack config) and consistency (dc will _exactly_ the same resolution extensions whether the dependency is included directly or via an aliasing mechanism).
This expands upon #243.
- My change doesn't require a change to the documentation, or ...
- it does and I have updated it
> bugfix(main): align regular and tspath resolution extensions & order

- src/report/err-html/err-html.template.hbs
- src/report/err-html/err-html.template.js
- When you click on the name of a rule in the summary of your violation report, the report will navigate to the first dependency that violated the rule.
If there's a _lot_ of rule violations it's practical to navigate directly to the first violation of a certain type to see what's violating it a.o.t. `ctrl-F` 'ing it.
eyeballs + automated non-regression testing
> feature(report): err-html: click on rule = navigate to details

- src/report/dot/index.js
- test/report/dot/customLevel/mocks/dependency-cruiser-2020-01-25.dot
- test/report/dot/customLevel/mocks/rxjs.dot
- the custom level graph reporter still emitted dummy nodes - which are only necessary for the dir level reporter
- simplifies the output (and makes dot happier)
Automated non-regression tests, adapted automated tests - green CI
> bugfix(report): don't emit dummy nodes in the custom level dot reports

- package.json
- src/report/dot/compareRules.js
- src/report/dot/consolidateModuleDependencies.js
- src/report/dot/consolidateModules.js
- test/report/dot/compareRules.spec.js
- see title
previously just concat'ing the rules - in typical set-ups this will work just fine, but if there's > 1 violated rule per aggregated dependency the most important (severe) one should be on top - and be displayed in any visuals.
automated non-regression tests, additional unit tests
> bugfix(report): sort aggregated rules on severity

- src/report/html/html.template.hbs
- src/report/html/html.template.js
- test/cli/fixtures/cjs.dir.filtered.html
- test/report/html/mocks/cjs-no-dependency-valid.html
On hovering cells in the html  matrix report highlight the vertical as well as the horizontal rows.
Eases use 
Automated non-regression, green ci
> feature(report): add vertical highlight to the html table report

- src/extract/utl/compare.js
- test/extract/utl/compare.dependenciesEqual.spec.js
- test/extract/utl/detectPreCompilationNess.spec.js
Disregards the module system when determining pre-compilation-ness.
In typescript the module system will typically be es6. Compiled down to
javascript it can be es6, but also cjs (depends on the `module` setting
in your tsconfig). In the latter case, we're still looking at the same
dependency even though the module systems differ.
Automated non-regression tests, adapted unit tests - live repos. Green CI.
> bugfix(extract): disregards the module system when determining pre-compilation-ness

- src/report/dot/defaultTheme.json
- By default in dot reports, if a dependency is determined to be pre-compilation only (with the option `tsPrecompilationDeps: "specify"`) they will now show up visually distinguishable from post-compilation-also dependencies (currently with an open instead of a closed arrow, and with a slightly smaller line thickness).
This was already possible by using a customised theme 
- You might want to treat dependencies that exist before compilation only (e.g. type imports) different from others. Having them visually distinguished by default will aid in making these decisions.
Eyeballs. Green CI.
This gives an overview of [http-proxy-middleware](chimurai/http-proxy-middleware)'s internal and external dependencies. You'll see that all dependencies on `types.ts` as well as the external dependency on …
> feature(report): by default visually distinguishes pre-compilation only dependencies in all dot reports

- test/extract/ast-extractors/allShapesOfImportExport.md
- test/extract/ast-extractors/extract-typescript-exports.spec.js
- test/extract/ast-extractors/extract-typescript-imports.spec.js
… and keep working
typescript 3.8 introduces [type only imports](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/#type-only-imports-exports) and [export yadda as namespace](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/#export-star-as-namespace-syntax). This PR makes sure it works and will verifiably keep working by adding unit tests (it already worked out of the box).
Automated non-regression tests, new unit tests, green CI.
> test(extract): add unit tests to verify new types of imports & exports in typescript 3.8+ work

- types/options.d.ts
Fix type declaration for options.doNotFollow.dependencyTypes. All uses in the code base are passing in an array so I assume that is the expected type.
The `dependencyTypes` property of the option `doNotFollow` is [documented as accepting an array](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#specifying-dependency-types-in-donotfollow) of DeclarationType: `DeclarationType[]`. This is currently not reflected in the type declaration files.
I ran `npm run check:full` but this is a tiny type change so I'm not sure if anything is testing that anyway.
- The contribution is my …
> require array for doNotFollow.dependencyTypes

- doc/assets/theming/engineering.svg
- doc/faq.md
- doc/real-world-samples/dependency-cruiser-dir-graph.svg
- doc/real-world-samples/dependency-cruiser-without-node_modules.svg
- doc/rules-reference.md
- docs/dependency-cruiser-dependency-graph.html
- package.json
- src/extract/gather-initial-sources.js
- test/extract/gather-initial-sources.spec.js
Exclude files that match the doNotFollow pattern in the first extraction pass (gathering files from disk based on the arguments passed), so they won't (unexpectedly) get fully traversed.
- Potentially fixes #281
- When the user passes doNotFollow she's probably not directly interested in them, even when she passes them as part of the arguments she passes (e.g. even though node_modules get matched by `packages/*`or `./` - if she's passing node_modules as doNotFollow she wouldn't care less about node_modules content other then the first thing the rest of her code is touching in there).
- As far as I could see there's no real non-regression involved 
- Additional unit tests
- Automated non-regression tests
- Green ci
- Live test against a warty mono repo
- My change doesn't require a …
> feature(extract): do not gather doNotFollow pattern

- doc/real-world-samples/dependency-cruiser-without-node_modules.svg
- docs/dependency-cruiser-dependency-graph.html
- package.json
- src/extract/transpile/meta.js
- test/extract/resolve/fixtures/vue-last/x.ts
- test/extract/resolve/fixtures/vue-last/y.ts
- test/extract/resolve/fixtures/vue-last/y.vue
- test/extract/resolve/index.spec.js
- test/extract/transpile/meta.spec.js
See title
Fixes #291 
- Additional unit tests
- Green CI
> bugfix(resolve): changes default resolve order so .vue is resolved after regular language suffixes (like .ts)

- src/schema/cruise-result.schema.json
- src/validate/match-dependency-rule.js
- test/report/anon/anonymize.spec.js
- test/report/anon/fixtures/cycle.json
- test/report/anon/fixtures/src-report-wordlist.json
- test/report/anon/fixtures/src-report.json
- test/report/anon/mocks/cycle.json
- test/report/anon/mocks/src-report-wordlist.json
- test/report/anon/mocks/src-report.json
- test/validate/index.pre-compilation-only.spec.js
- types/cruise-result.d.ts
- utl/schema/dependencies.mjs
The attributes "circular" and "exoticallyRequired" are always present in the result tree. This PR makes them both mandatory in the json schema and the type declarations) so it's clear they can be used safely without null checks (note: exoticallyRequired already was mandatory in the type declarations).
> bugfix(schema|types): make circular and exoticallyRequired mandatory in schema and type declarations

- .dependency-cruiser.json
- src/cli/defaults.json
- src/cli/init-config/add-run-scripts-to-manifest.js
- src/cli/init-config/build-config.js
- src/cli/init-config/environment-helpers.js
- src/cli/init-config/get-user-input.js
- src/cli/init-config/index.js
- src/cli/init-config/inquirer-validators.js
- src/cli/init-config/normalize-init-options.js
- src/cli/init-config/write-config.js
- src/report/error.js
- src/utl/wrap-and-indent.js
- test/cli/init-config/add-run-scripts-to-manifest.spec.js
- test/cli/init-config/environment-helpers.spec.js
- test/cli/init-config/index.spec.js
- test/cli/init-config/inquirer-validators.spec.js
- Adds an experimental one shot `--init` config that automatically adds some useful run scripts to package.json.
Basic undocumented feature to gauge impact, usefulness & gremlins. Later on this might be converted into one or more of the inquirer questions and/ or a separate init option, that can be run anytime. 
>For those who want to try and don't want to rely on the git branch: this PR is released npm as `dependency-cruiser@9.5.0-beta-1`
Seems useful; when you want to quickly instrument a repo to not have to manually type stuff into your package.json.
- I am ok …
> feature(init): add manifest run scripts one shot config

- src/cli/init-config/environment-helpers.js
- src/cli/init-config/get-user-input.js
- src/cli/init-config/index.js
- src/cli/init-config/normalize-init-options.js
- test/cli/init-config/environment-helpers.spec.js
- test/cli/init-config/normalize-init-options.spec.js
- If the current folder looks like a mono-repo, use the folder with _packages_ in them (user specifiable, defaulting to `packages`) for sources and (for now) skip any test folder questions
dependency-cruiser is useful especially in big and humongous repositories. So setup should be peanuts for the first time user.
> feature(init): basic mono-repo config init

- .dependency-cruiser.json
- doc/rules-reference.md
- src/main/rule-set/normalize.js
- src/main/utl/normalize-re-properties.js
- src/schema/README.md
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.json
- test/main/rule-set/normalize.spec.js
- test/main/utl/normalize-re-properties.spec.js
- tools/README.md
- tools/schema/restrictions.mjs
- types/reporter-options.d.ts
- types/rule-set.d.ts
- Allows `path` and `pathNot` to accept an array of RE'sin addition to just a string, so in stead of 
```javascript
{
from: {
path: "(^src/report/)"
},
to: {
pathNot: "$1|^node_modules|^(path|package.json)$|^src/utl"
}
}
```
... you can now write like this in stead, which will more legible in many situations:
```javascript
{
from: {
path: "(^src/report/)"
},
to: {
pathNot: [
"$1",
"^node_modules",
"^(path|package.json)$",
"^src/utl"
]
}
}
```
- does the same for the `license`, `licenseNot`, `exoticRequire` and `exoticRequireNot` attributes
- for `path` and `pathNot`: fixes #316 
- for the other attributes: consistency is the king of DX
- The contribution will be subject to [The MIT …
> feature(*): allows path and pathNot to accept an array of RE's

- .dependency-cruiser.json
- doc/rules-reference.md
- src/main/options/normalize.js
- src/main/utl/normalize-re-properties.js
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.json
- test/main/options/normalize.spec.js
- tools/schema/compound-donot-follow-type.mjs
- tools/schema/compound-exclude-type.mjs
- tools/schema/compound-focus-type.mjs
- tools/schema/compound-include-only-type.mjs
- tools/schema/options.mjs
- tools/schema/re-as-strings-type.mjs
- tools/schema/restrictions.mjs
- types/filter-types.d.ts
- types/options.d.ts
- types/reporter-options.d.ts
Just like #317, but for the filtering options instead of for rules. So now instead of writing
```javascript
options: {
doNotFollow: "^node_modules|vendor_stuff|not/very/interesting_either"
}
```
you could write in stead 
```javascript
options: {
doNotFollow: [
"^node_modules",
"vendor_stuff",
"not/very/interesting_either"
]
}
```
or 
```javascript
options: {
doNotFollow: {
path: [
"^node_modules",
"vendor_stuff",
"not/very/interesting_either"
]
}
}
```
Implemented for all filter options: _doNotFollow_, _exclude_, _includeOnly_ and _focus_.
> The same expansion will be implemented for reporter options that accept RE's - in a separate PR, though
Ease of use & readability, just like in #317 
- The …
> feature(*): allow filter options to accept an array of RE's

- .dependency-cruiser.json
- doc/rules-reference.md
- src/cli/parse-babel-config.js
- test/cli/fixtures/babelconfig-js/babel.config.wildly-unsupported-extension
- test/cli/fixtures/babelconfig-js/babel.es-module.config.js
- test/cli/fixtures/babelconfig-js/babel.function-export.config.js
- test/cli/fixtures/babelconfig-js/babel.object-export.config.js
- test/cli/parse-babel-config.spec.js
Adds support for babel configurations expressed in (commonjs) javascript that export a plain javascript object.
Covers some more babel usage scenarios, so dependency-cruiser becomes more usable in that space.
Support for babel configurations that export a function (`function(api) { /* blah */ return { /* config */} }`) and/ or that are written as es/ mjs modules will probably follow in a separate PR.
> feature(cli): enables reading babel configs from commonjs modules that export an object

- src/schema/cruise-result.schema.json
- tools/schema/dependencies.mjs
- types/cruise-result.d.ts
They were missing - which is problematic when you want to pass the output of a cruise to e.g. depcruise-fmt, which validates its input against the schema
> bugfix(schema|types): add the preCompilationOnly attribute of dependencies to the json schema and TypeScript types

- src/cli/defaults.json
- src/cli/init-config/index.js
- src/cli/init-config/write-config.js
- src/cli/normalize-options.js
- test/cli/init-config/fixtures/update-manifest-dc-config-exists/.dependency-cruiser.js
- test/cli/init-config/index.spec.js
- test/cli/normalize-options.spec.js
- use the base config when an unknown config id is passed
- instead of bailing out, silently skip writing to .dependency-cruiser.js if it already exists
- for experimental-scripts: even if a .dependency-cruiser.js already exists, still add to package.json
- assume .dependency-cruiser.js to be the default config in error messages instead of .dependency-cruiser.json
- also refactors reuse of a constant
- Eases use
- For the error message: closer to the truth in most installations nowadays
> feature(init): tweaks to one-shot configs

- bin/depcruise-fmt.js
- bin/dependency-cruise.js
- test/cli/utl/io.spec.js
Updates the copy of the dependency-cruise and depcruise-fmt commands & reorganises it a bit so it's easier to read 🤞 .
```
Usage: dependency-cruise [options] <files-or-directories>
Validate and visualize dependencies.
Details: https://github.com/sverweij/dependency-cruiser
Options:
--init [oneshot]              set up dependency-cruiser for use in your environment (<<<
recommended!)
-c, --config [file]           read rules and options from [file] (e.g. .dependency-cruiser.js)
-T, --output-type <type>      output type; e.g. err, err-html, dot, ddot, archi or json
(default: err)
-f, --output-to <file>        file to write output to; - for stdout (default: "-")
--include-only <regex>        only include modules matching the regex
--focus <regex>               only include modules matching …
```
> doc(cli): re-write the copy for the two commands

- src/enrich/add-validations.js
- src/enrich/enrich-modules.js
- src/validate/index.js
- test/validate/index.exotic-require.spec.js
- test/validate/index.groupmatching.spec.js
- test/validate/index.license.spec.js
- test/validate/index.orphans.spec.js
- test/validate/index.pre-compilation-only.spec.js
- test/validate/index.reachable.spec.js
- test/validate/index.required-rules.spec.js
- test/validate/index.spec.js
Moves the check whether or not to validate to the enrich part, so you don't have to pass a validate boolean to the validate function to get it to validate.
> refactor(enrich|validate): sanitize validate interface

- .dependency-cruiser.json
- doc/rules-reference.md
- package.json
- src/enrich/add-validations.js
- src/enrich/summarize-options.js
- src/enrich/summarize.js
- src/extract/clear-caches.js
- src/extract/index.js
- src/main/resolve-options/normalize.js
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.json
- src/validate/index.js
- src/validate/match-module-rule.js
- test/extract/resolve/local-npm-helpers.spec.js
- tools/schema/options.mjs
- types/options.d.ts
- makes it work with the new version of enhanced-resolve (v5.x.x - currently still in beta...)
- frees additional memory after the extract step by calling ehr's purge & clearing the memoization-caches (not only the nice to do, but also useful for those using the API and doing multiple cruises per session).
- adds an option in the configuration that enables you to tweak the enhanced-resolve's cached file system's cache duration (see below for an example - minimum duration: 0ms maximum duration: 1800000ms (0.5h))
- ~~lowers the default cache duration from 4000ms to 1000ms (both turn out to be approximately as fast, but the latter consumes way less memory).~~ (_keeps_ the cache duration at 4s as on slower file systems (and fast file systems with a virus scanner activated ...) the impact on …
> bugfix(extract): reduces memory usage by using new version of enhanced-resolve

- src/main/resolve-options/normalize.js
- test/extract/resolve/fixtures/package-json-with-exports/node_modules/export-testinga/feature.cjs
- test/extract/resolve/fixtures/package-json-with-exports/node_modules/export-testinga/feature.mjs
- test/extract/resolve/fixtures/package-json-with-exports/node_modules/export-testinga/main.cjs
- test/extract/resolve/fixtures/package-json-with-exports/node_modules/export-testinga/main.mjs
- test/extract/resolve/fixtures/package-json-with-exports/node_modules/export-testinga/package.json
- test/extract/resolve/fixtures/package-json-with-exports/yolo.cjs
- test/extract/resolve/fixtures/package-json-with-exports/yolo.mjs
- test/extract/resolve/index.spec.js
- test/main/resolve-options/normalize.spec.js
See title. For an explanation - see the 2nd response in the linked issue.
fixes #338 
> bugfix(resolve): by default don't let enhanced-resolve look at 'exports' fields in package.json manifests just yet

- src/enrich/de-duplicate-violations.js
- src/enrich/summarize-modules.js
- src/report/error-html/index.js
- test/enrich/de-duplicate-violations.spec.js
- test/main/fixtures/dynamic-imports/es/output.json
- test/main/fixtures/dynamic-imports/typescript/output-pre-compilation-deps.json
- test/main/fixtures/dynamic-imports/typescript/output.json
The reporters that use the summarised errors for or in their output (err, err-html, teamcity, json, anon and the api only 'identity') currently report each dependency in a cycle separately. This is correct and in line with other dependency violations. It's slightly impractical, though as each module in the cycle will show up once, whereas it's just one cycle. E.g this one cycle ...
would (correctly, but verbosely) yield:
```
error no-circular: src/report/anon/random-string.js → 
src/report/anon/index.js →
src/report/anon/anonymize-path.js →
src/report/anon/anonymize-path-element.js →
src/report/anon/random-string.js
error no-circular: src/report/anon/index.js → 
src/report/anon/anonymize-path.js →
src/report/anon/anonymize-path-element.js →
src/report/anon/random-string.js → …
```
> feature(enrich): de-duplicate cyclic violations in the summary

- bin/depcruise-fmt.js
- bin/dependency-cruise.js
- doc/cli.md
- doc/rules-reference.md
- src/cli/format.js
- src/enrich/summarize-modules.js
- src/main/index.js
- src/main/options/normalize.js
- src/main/options/validate.js
- test/cli/format.spec.js
- test/main/main.format.spec.js
- Adds three command line filtering options to depcruise-fmt (--include-only, --focus, --exclude) that work the same as the ones on the depcruise command.
- Also adds short versions for the filter commands to the `depcruise` command (-I and -F respectively) to be consistent with depcruise-fmt and to make it easier to use if you're using the cli to interrogate.
- On the fly fixes an as of yet undetected bug where a reportOptions.dot/archi/ddot.filters.focus wasn't taken into account.
`depcruise-fmt` is useful if you want to display the results of the same cruise in different ways, without having to run the cruise repeatedly. Especially on bigger code bases this can save time. Cruising all code can sometimes take more than a minute, while formatting usually takes well below a second.
Adding …
> feature(depcruise-fmt): add filter options

- src/cli/index.js
When the `progress` option is on (undocumented yet - experimental), and dc encountered an error situation it emitted an `end` event. The listeners typically write some close remarks and then close the stream.
```javascript
bus.emit('end');
// errors when there's a listener on the bus that just closed the stream on stderr
process.stderr.write(`something went wrong yadda\n`);
```
When we use `process.stderr` as the stream the listener writes to, after bus.emit, `stderr` is already closed, resulting in an erroring error message about trying to write after the stream is closed.
This fix fixes that bug.
> The problem does not occur when not using the `progress` option (which you probably don't do in the first
> place as it's still experimental).
- My change doesn't require a documentation …
> bugfix(cli): print errors normally also when handling progress feedback

- .dependency-cruiser.json
- src/report/dot/default-theme.json
- test/report/dot/folder-level/mocks/dependency-cruiser-2019-01-14.dot
Dashed lines aren't particularly easy to follow, and definitely not when there's a lot of them. Dependencies to node_modules were by default represented as dashed lines. Changed this default to a solid line.
> bugfix(dot): better default for presenting dependencies to node_modules

- src/cli/compile-config/index.js
- src/cli/init-config/environment-helpers.js
- src/cli/init-config/normalize-init-options.js
- src/cli/parse-babel-config.js
- src/enrich/derive/reachable/index.js
- src/enrich/summarize-options.js
- src/extract/index.js
- src/extract/resolve/determine-dependency-types.js
- src/extract/resolve/local-npm-helpers.js
- src/main/rule-set/normalize.js
- src/main/rule-set/validate.js
- src/report/dot/theming.js
- src/report/error-html/utl.js
- src/validate/index.js
- src/validate/is-module-only-rule.js
- src/validate/match-dependency-rule.js
- src/validate/match-module-rule.js
- test/extract/resolve/local-npm-helpers.spec.js
See title. Improves readability
> refactor: replaces Object.property.hasOwnProperty.call with _.has

- src/cli/tools/svg-in-html-snippets/footer.snippet.html
I was playing around with making a dark theme, and the output html got formatted and this broke my highlighting code, since it introduced whitespace. This is a small tweak to fix that.
in `.dependency-cruiser.js`
```js
const darkTheme = {
graph: {
bgcolor: 'black',
fontcolor: 'white',
fillcolor: '#000000',
},
node: {
color: 'gray',
// fillcolor: '#000033',
// fontcolor: 'white'
},
edge: {
color: '#FFFFFF33',
},
};
module.exports = {
// ...
options: { reporterOptions: { dot: { theme: darkTheme } } }
};
```
in `svg-in-html-snippets/header.snippet.html`
```html
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8" />
<title>dependency graph</title>
<style>
html,
body {
background-color: black;
scrollbar-color: DimGray black;
}
.cluster:active path,
.cluster:hover path {
fill: #33330011;
} …
```
> fix: allow highlighting to work after formatting the html

- src/main/index.js
On a `depcruise-fmt output.json -T archi` depcruise-fmt didn't heed the collapsePattern defined for the archi reporter. This PR makes sure it does.
> bugfix(depcruise-fmt): only override dot collapse when it's provided

- src/extract/resolve/index.js
- test/extract/resolve/fixtures/donot-resolve-to-non-ts/there-is-a-cjs-variant-of-me-but-you-will-not-find-it.cjs
- test/extract/resolve/fixtures/resolve-to-ts-even-when-imported-as-js/i-am-secretly-typescript.ts
- test/extract/resolve/index.spec.js
This is currently the typescript compiler's default behavior, so we follow suit. 
Fixes #364 
TODO
- some research shows that this only applies to typescript and only for Microsoft's typescript compiler and only for .js/.jsx => .ts/ .tsx/ .d.ts. It's really deliberate (explicitly including .ts makes the compiler relapse in horror) so it's going to be made more specific in order to not induce any breaking changes.
- feature switch is not necessary if we narrow it down to only js/jsx going in and something typescript-ish coming out of the retry (extensions ts and tsx). That way it won't start to all-of-a-sudden start to do weird resolves in any non-ts environment.
- the solution should _actually_ be in enhanced_resolve (either by default or by way of a plugin).
see issue
- My change doesn't …
> bugfix(resolve): try other extensions even when importing with explicit extension

- src/extract/resolve/determine-dependency-types.js
- test/extract/resolve/determine-dependency-types.spec.js
See title
So when you have e.g. a `hodash` dependency and a ~@types/hodash~ devDependency they're not (1) flagged as duplicate dependencies (2) the @types devDependency isn't flagged in a not-to-dev rule. Which both would be false positives.
> bugfix(resolve): don't count regular and @types in package.json as two separate things

- src/report/error-long.js
- src/report/index.js
- test/main/main.format.spec.js
- test/report/error/error-long.spec.js
- Makes the error-long reporter invocation un-fancy, so it prints comments/ explanations again
Since the moment reporter invocation in `main` was made more generic parameters weren't passed correctly anymore to the error-long reporter (which in itself still worked fine :-/)
Fixes a bug (error-long is expected to print the comments)
> bugfix(report): make the err-long reporter print comments again

- README.md
- doc/cli.md
- doc/rules-reference.md
- src/cli/init-config/write-run-scripts-to-manifest.js
and only mention the alternate .json when really relevant
- Updates documentation as in title
fixes #383 
> bugfix(doc): consistently use .dependency-cruiser.js as config file name

- .github/workflows/lint-test-workflow.yml
- .github/workflows/test-workflow-windows-only.yml
- package.json
- src/enrich/summarize-options.js
- src/extract/gather-initial-sources.js
- src/extract/index.js
- src/extract/resolve/index.js
- src/extract/resolve/resolve-amd.js
- src/extract/resolve/resolve-cjs.js
- src/extract/resolve/resolve.js
- src/extract/utl/path-to-posix.js
- test/cli/parse-ts-config.spec.js
- test/extract/gather-initial-sources.spec.js
- test/extract/utl/path-to-posix.spec.js
- test/main/main.cruise.spec.js
- Moves converting paths to posix earlier in the process and removes the conversion where the conversion doesn't have any effect anymore.
See #386 - @tvolodimir put me on this trail that path-to-posix has an impact on performance. On msdos derivatives this refactor tends to make a significant difference in performance - on an i5 with win10 dependency-cruiser cruises itself in ~27s instead of in 32s (which is still ~3x as slow as it's on unix derivatives, but it's a start).
> refactor(extract): call path-to-posix less often

- doc/faq.md
- package.json
- src/extract/ast-extractors/extract-es6-deps.js
- src/extract/parse/to-javascript-ast.js
- src/extract/transpile/jsx-implementation-rationale.md
- src/extract/transpile/meta.js
- test/extract/ast-extractors/extract-es6-deps.spec.js
dependency-cruiser shirked back from using acorn-jsx + acorn-jsx-walk because it didn't look like a stable solution and straight acorn + acorn-loose worked correctly in all jsx cases thrown at them. Today @audunsol raised #395, showing a counter example.  acorn-jsx-walk's code today (and with today's eyes) looks totally simple and solid to use, so this PR can use it to ensure dependency-cruiser parse jsx with the official acorn-jsx plugin.
fixes #395 
> bugfix(extract): use acorn-jsx for parsing jsx (instead of acorn + acorn-loose)

- src/cli/listeners/cli-feedback/index.js
- src/cli/listeners/performance-log/index.js
- src/enrich/enrich-modules.js
- src/main/index.js
Adds a % complete to the `cli-feedback` --progress option
Shows more information
Before: 
```
▶ reading files ...
```
After:
```
◼◼◼◼◼◼◻◻◻◻ 63% reading files ...
```
> feature(cli): adds showing % complete in cli-feedback

- .dependency-cruiser.json
- configs/recommended.js
- src/cli/format-meta-info.js
- src/cli/index.js
- src/cli/utl/validate-file-existence.js
- src/extract/ast-extractors/extract-amd-deps.js
- src/extract/ast-extractors/extract-cjs-deps.js
- src/extract/ast-extractors/extract-es6-deps.js
- src/extract/ast-extractors/extract-typescript-deps.js
- src/extract/gather-initial-sources.js
- src/extract/get-dependencies.js
- src/extract/index.js
- src/extract/transpile/coffeescript-wrap.js
- src/extract/transpile/index.js
- src/extract/transpile/svelte-wrap.js
- src/extract/transpile/typescript-wrap.js
- src/extract/utl/detect-pre-compilation-ness.js
- src/extract/utl/get-extension.js
- src/main/files-and-dirs/normalize.js
- src/main/resolve-options/normalize.js
- src/main/rule-set/normalize.js
- src/main/rule-set/validate.js
- Closes #409 
- Also makes named functions of module exports that were still anonymous - so they;re easier to identify in profiling tools.
- ... and simplifies some of the extract code 
> refactor(extract): excludes excludable file name patterns earlier

- package.json
:arrow_down: enhanced-resolve to 5.1.0 as 5.2.0 and up seem to have a performance regression.
- Brings down the execution time on dependency-cruiser itself down from ~5.3s to ~3.4s (windows) and ~2.9s to ~2.1s (linux)
- ehr is now pinned to 5.1.0 as long as the performance regression is in (or when functionality in 5.4 and up becomes more important than performance regression).
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/develop/.github/CONTRIBUTING.md) …
> buid(npm): :arrow_down: enhanced-resolve to 5.1.0

- src/cli/init-config/get-user-input.js
see title
fixes #416 (which was introduced in release 9.21.2, commit 090e6774)
> bugfix(init): explicitly pass no params to ts config detector

- src/main/resolve-options/normalize.js
- test/main/fixtures/tsconfig.test.json
- test/main/resolve-options/normalize.spec.js
tsconfig-paths-plugin has a measurable impact (~10ms for 15 resolutions) even when there's no paths in the tsconfig. Hence only loading it when there's _and_ a baseUrl _and_ paths will improve performance for those not using _paths_ in their tsconfig 
> perf(resolve): only load tsconfig-paths-plugin when there's at least one defined path in tsconfig

- src/cli/index.js
requiring init-config takes ~100ms (most of it taken up by requiring inquirer, measured on a 2.6GHz quad core i7 with flash storage on macOS 10.15.7). Only requiring it when --init is necessary speeds up (the start-up) of cruises by that same amount.
> perf: restricts requiring init-config (/ inquirer) to when it's necessary

- src/config-utl/extract-babel-config.js
- test/config-utl/extract-babel-config.spec.js
Under certain circumstances babel expects a filename together with the contents of the babel config. This PR makes sure babel always has a filename to use.
Adresses #421 
> bugfix(babel): also pass a filename to babel when parsing a config

- src/extract/parse/to-javascript-ast.js
- src/extract/transpile/babel-wrap.js
- src/extract/transpile/index.js
- src/extract/transpile/svelte-preprocess.js
- src/extract/transpile/svelte-wrap.js
- src/extract/transpile/typescript-wrap.js
- test/extract/ast-extractors/extract-amd-deps.spec.js
- test/extract/ast-extractors/extract-cjs-deps.spec.js
- test/extract/ast-extractors/extract-es6-deps.spec.js
- test/extract/transpile/babel-wrap.spec.js
- test/extract/transpile/index.spec.js
- Adds a _filename_ parameter to all transpiler wrapper functions so underlying transpilers can have fun with it.
Some of the transpilers use the file name them for decorative purposes, some (e.g. babel with some plugins) really use the filename to determine how to transpile things. This is one step in the direction of fixing interesting behavior of the babel api uncovered in #421.
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/develop/.github/CONTRIBUTING …
> refactor(transpile): also pass a filename to the transpilers

- src/extract/parse/to-javascript-ast.js
- test/extract/ast-extractors/extract-typescript.utl.js
- test/extract/parse/to-javascript-ast.spec.js
When a tsx is compiled down with the tsc option 'preserve' we can pass it to acorn-jsx (who knows how to handle it) instead of to acorn.
This fixes a (corner case) bug:
- Use a .tsx source with import, export or require keywords in a tag
- Use `"jsx": "preserve" in tsconfig.json
- Keep tsPreCompilationDeps on _false_ in the dependency-cruiser config
This way dependency-cruiser would pass a piece of jsx source code to the acorn parser, instead of to acorn-jsx. Acorn would be confused - so dependency-cruiser would pass it to the loose version of the acorn compiler - leading to the side-effects earlier uncovered in #395 for regular jsx.
- The contribution will be subject to [The MIT …
> bugfix(parse): preserve tsx-ness in the ts-via-acorn route

- src/report/dot/theming.js
Every call to cruise with cruiseOptions containing theme modules would leak those theme modules into all subsequent runs because theme modules are modifying DEFAULT_THEME directly.
DEFAULT_THEME is mutated on e.g. line 40 where `pTheme.modules` are concatenated in. This results in the accumulation of theme modules, corrupting subsequent invocations.
I was running the cruise command programmatically with different theme modules per invocation and noticed the leak, which fundamentally prevents me from using dependency cruiser programmatically. 
I've only done manual inspection of my output at this point. If this PR has interest I'm happy to be pointed towards further testing efforts to solidify the fix.
- it _does_ and I have …
> fix bug where multiple runs leak theme modules

- doc/options-reference.md
- src/extract/gather-initial-sources.js
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.json
- test/extract/gather-initial-sources.spec.js
- test/main/fixtures/cruise-reporterless/commonjs.json
- tools/schema/options.mjs
- types/options.d.ts
Running a scan with cruiseOptions `baseDir` set almost works, but actually results in various errors and bad scenarios because the run always sees `fileDirectoryArray` as relative to `process.cwd()` instead of the path specified in `baseDir`.
When calling dependency cruiser programmatically my understanding is specifying `baseDir` in cruiseOptions should be as if I ran `depcruise` in the shell from that folder. But `gatherScannableFilesFromDirectory` breaks that because it calls `readdirSync(pDirectoryName)` which *implicitly* relies on cwd when passed a relative path. If we instead join `pOptions.baseDir` into that path then `pDirectoryName` gets resolved according to `baseDir`.
By default `baseDir` is cwd so this doesn't change existing functionality, but allows the caller to override …
> fix bug where baseDir is ignored when calling programmatically

- .dependency-cruiser.json
- src/enrich/derive/reachable/index.js
- src/schema/cruise-result.schema.json
- src/validate/match-module-rule.js
- test/cli/fixtures/result-has-a-dependency-violation.json
- test/enrich/derive/reachable/index.spec.js
- test/validate/fixtures/rules.reachable.capturing-group.json
- test/validate/index.reachable.spec.js
- tools/schema/modules.mjs
- types/cruise-result.d.ts
- Adds support for capturing groups on rules that have a 'reachable' attribute.
- See #442 for an example rule and an expected output
- Todo:
Fixes #442 
Published with beta tag as `dependency-cruiser@9.23.1-beta-1`
*= could be construed as a new feature - but as the documentation doesn't mention it doesn't work you might assume that it does work - so classifying it as a bug nonetheless.
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/develop/.github/CONTRI …
> bugfix(enrich): adds support for capturing groups on 'reachable' rules

- configs/plugins/stats-reporter-plugin.js
- src/enrich/derive/dependents/get-dependents.js
- src/enrich/derive/dependents/index.js
- src/enrich/derive/orphan/index.js
- src/enrich/enrich-modules.js
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.json
- test/enrich/derive/dependents/get-dependents.spec.js
- test/main/fixtures/collapse-after-cruise/expected-result.json
- test/main/fixtures/cruise-reporterless/amd.json
- test/main/fixtures/cruise-reporterless/bundled-dependencies.json
- test/main/fixtures/cruise-reporterless/coffee.json
- test/main/fixtures/cruise-reporterless/commonjs.json
- test/main/fixtures/cruise-reporterless/deprecated-node-module.json
- test/main/fixtures/cruise-reporterless/typescript.json
- test/main/fixtures/cruise-reporterless/vue.json
- test/main/main.cruise-reporterless.spec.js
- tools/regenerate-main-fixtures.utl.js
- tools/schema/modules.mjs
- tools/schema/options.mjs
- types/cruise-result.d.ts
- types/options.d.ts
Adds an array of `dependents` to each module when asked to. As this is potentially an expensive operation, it's feature switched - currently with `forceDeriveDependents` in the `options` object. Later on we'll look whether there's rules (i.e. on how often a module is used) and/ or reporter options (i.e. `focus`) that either need these or will benefit from them.
So we can use them more easily in rules later on - e.g. to create rules based on the amount of dependents a module should have (see #445)
- I am ok …
> feature(enrich): adds dependents to each module

- doc/rules-reference.md
- doc/rules-tutorial.md
- src/enrich/derive/dependents/index.js
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.json
- src/validate/match-module-rule.js
- test/validate/match-module-rule.dependents.spec.js
- tools/schema/restrictions.mjs
- types/restrictions.d.ts
Adds a `numberOfDependentsMoreThan` attribute to the schema and enables using it in `forbidden` rules. It was made for `allowed` rules (see below), but that will follow in a separate PR.
TL;DR - so later on 'shared' rules can be enforced in the 'allowed' type of rulesets. And maybe handy for enforcing deprecation.
If you want to enforce a module is shared a minimum number of times, you can currently put a rule like this in the `forbidden` section of your configuration using the `numberOfDependentsLessThan` attribute, e.g.:
```javascript
// ... somewhere in a 'forbidden' rule set
{
name: "no-unshared-in-common",
from: {
pathNot: "^src/common"
},
module: {
path: "^src/common",
numberOfDependentsLessThan: 2
}
}
// ...
```
However, you currently can't do the same in a `allowed` rules. As the …
> feature(validate): adds a dependents count > check

- .dependency-cruiser.json
- doc/options-reference.md
- package.json
- src/extract/ast-extractors/extract-swc-deps.js
- src/extract/ast-extractors/extract-typescript-deps.js
- src/extract/ast-extractors/swc-dependency-visitor.js
- src/extract/clear-caches.js
- src/extract/get-dependencies.js
- src/extract/parse/to-swc-ast.js
- src/extract/transpile/meta.js
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.json
- test/extract/ast-extractors/extract-typescript-type-imports.spec.js
- test/extract/ast-extractors/extract-with-swc-commonjs.spec.js
- test/extract/ast-extractors/extract-with-swc-dynamic-imports.spec.js
- test/extract/ast-extractors/extract-with-swc-exotics.spec.js
- test/extract/ast-extractors/extract-with-swc-exports.spec.js
- test/extract/ast-extractors/extract-with-swc-imports.spec.js
- test/extract/ast-extractors/extract-with-swc-type-imports.spec.js
- test/extract/ast-extractors/extract-with-swc.utl.js
- test/extract/get-dependencies.spec.js
- test/extract/transpile/meta.spec.js
- tools/schema/options.mjs
- types/.dependency-cruiser.json
- Adds `swc` to the two parsers already in use
- Adds a 'parser' option to enable swc explicitly
- Currently only works when `@swc/core` is installed in the same spot dependency-cruiser is (it might become a permanent dependency, though - it weighs about 10kb including dependencies).
`swc` seems to be (quite) a bit faster than existing parsers written in javascript (tsc, acorn). Using it in place of acorn (and implementing hamfistedly) made a difference of ~120ms over the code base of dependency-cruiser (~2070ms -> ~1950ms), shaving about that amount off of the most time consuming step (visiting dependencies; ~920ms => ~800ms). Expect this to be bigger on larger projects.
This option is _experimental_ for now. I first want to see it perform in some gnarly code bases for some time before …
> feature(parse): adds swc as an alternative to the acorn and tsc parsers

- src/extract/ast-extractors/extract-swc-deps.js
- src/extract/ast-extractors/swc-dependency-visitor.js
- test/extract/ast-extractors/extract-with-swc-type-imports.spec.js
- the type annotations (that is to say: only a subset of the typescript spec) swc supports are now detected as ell.
- all AST traversal now happens within the Visitor, which makes it easier to maintain (and should be a little bit better for performant as we now do less).
> refactor(swc): adds typeAnnotation detection, refactors

- src/extract/get-dependencies.js
- src/extract/utl/extract-module-attributes.js
- src/schema/cruise-result.schema.json
- test/extract/utl/extract-module-attributes.spec.js
- tools/extract-line-coverage-from-istanbul-json.mjs
- tools/generate-schemas.utl.mjs
- tools/schema/dependencies.mjs
- types/cruise-result.d.ts
- types/shared-types.d.ts
- Adds recognition of protocol and mime type in module references so things like `import * as fs from 'node:fs'` and `import lalala from 'file:application/json,holadijee.json'` get recognised.
- Adds them to the cruise output model for later use
The new `protocol` and `mimeType` attributes aren't used anywhere yet - this might follow in next PR's
TIL: you can specify a [protocol (and mime type) with ES modules references](https://nodejs.org/api/esm.html#esm_urls). As @sindresorhus is pushing for its use (see [this issue in the nodejs repo](https://github.com/nodejs/node/issues/38343) and the new [prefer-node-protocol](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md) rule in eslint-plugin-unicorn) it'll likely become more commonplace.
- My …
> feature(extract): adds basic support for ESM urls (a.o. the node: protocol)

- src/validate/match-module-rule.js
- test/validate/match-module-rule.dependents.spec.js
It looks like the minimum/maximum dependents count does not correctly filter from `from.pathNot`. Specifically I was getting weird results when I was trying to find files only referenced by test files.
> Leave an [issue](https://github.com/sverweij/dependency-cruiser/issues/new) with a
> do that.
I negated the pathNot matching in the dependents filtering logic.
For some reason I cannot wrap my head around the tests that already exist so I made my own simple test that is not included in this pr.
```const USED_BY_APP = {
from: {
pathNot: ".test.ts$",
},
module: {
path: "^src",
numberOfDependentsLessThan: 1,
},
};
it("should complain about files that are only used by tests", () => { …
```
> correctly filter out dependents from pathNot

- src/extract/resolve/index.js
- test/extract/resolve/index.spec.js
- in resolved filenames replaces hashmarks prefixed with a NULL (\u0000) with just that hashmark
Hashmarks in filenames present resolvers with a problem as they can mean one of two things:
- the hashmark is part of the filename: `./some/dir/#/am-in-a-dir-with-a-hashmark.js` `./sim#salabim.js`
- the hashmark is a [fragment](https://en.wikipedia.org/wiki/URI_fragment) token in the URI: `./thing/thang/do-stuff.js#but-not-so-fast`
As part of the algorithm treating these variants enhanced-resolve, after resolving [inserts a NULL character in front of the hashmark](https://github.com/webpack/enhanced-resolve/blob/main/lib/Resolver.js#L282). Obviously, after that the 'resolved' filename doesn't 1:1 correspond to a real filename anymore. 
This PR removes those NULL characters again, so filenames …
> bugfix(resolve): work around enhanced-resolve's hashmark-in-filenames problem

- src/extract/ast-extractors/extract-swc-deps.js
- src/extract/ast-extractors/swc-dependency-visitor.js
As a remnant of a previous setup running through the swc AST there was an unnecessary extra function call that made the swc extraction function look more complicated than it actually was => this PR remedies that.
> refactor(swc): consolidate swc call

- bin/wrap-stream-in-html.js
- src/cli/tools/wrap-stream-in-html.js
- test/cli/tools/wrap-stream-in-html.spec.js
If the size of svg wrapped in the stream passes a certain threshold,  the buffer in `get-stream` can get bigger than memory allows, and the string to construct the output will be bigger than allowed. By removing these buffers from the equation, these problems will go away.
> bugfix(wrap-stream-in-html): de-buffer so it can handle larger streams

- src/config-utl/extract-ts-config.js
- see title
- released on npmjs as `dependency-cruiser@10.0.8-beta-1`
TODO:
- ~additional automated regression test against yarn 3 (and 2 f.t.m.)~ will be part of the fix for #471 
fixes #480 
> bugfix(ts-config): pass an absolute path to tsconfig.json so typescripts config parsing still works under yarn 3

- src/extract/resolve/index.js
- test/extract/resolve/fixtures/triple-slash-directives/node_modules/something/package.json
- test/extract/resolve/fixtures/triple-slash-directives/package.json
- test/extract/resolve/index.spec.mjs
Triple slash directives weren't put through the resolution algorithm. As a consequence something like ...
```typescript
/// <reference types="next" />
```
caused dependency-cruiser to mark the dependency between the file and the (external) `next` module as unresolvable. 
- Fixes a bug
- Addresses one of the two issues described in #471 
> bugfix(resolve): also puts triple slash directive dependencies through the resolution mill

- src/extract/resolve/index.js
- types/resolve-options.d.ts
- When running under yarn 2 & 3 (berry) resolves any virtual dependencies in a more palatable form
Fixes #471 
> feature(resolve): resolve yarn virtual dependencies

- .dependency-cruiser.json
- .github/workflows/berry-integration-workflow.yml
- .gitignore
- package.json
- adds a workflow for checking whether dependency-cruiser generally works under yarn berry
- updates .dependency-cruiser config to deal with some of the differences between npm based package management and yarn's plug'n play
yarn/ berry is used in the wild & we want to ensure dependency-cruiser works ok with it.
> chore(ci): adds a workflow for running under yarn/berry

- doc/options-reference.md
- src/extract/get-dependencies.js
- src/extract/parse/to-typescript-ast.js
- test/extract/get-dependencies.spec.mjs
- makes it possible to use tsc as the primary parser in addition to acorn (the default one) and swc
- adds symmetry
- makes it easier to switch transpilers in integration test scenario's
> feature(extract): makes it possible to use tsc as the primary parser

- doc/rules-reference.md
- src/main/utl/normalize-re-properties.js
- src/schema/configuration.schema.js
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.js
- src/schema/cruise-result.schema.json
- src/validate/match-dependency-rule.js
- src/validate/matchers.js
- test/validate/fixtures/rules.cycle.via-not.json
- test/validate/fixtures/rules.cycle.via.json
- test/validate/index.cycle-vias.spec.mjs
- test/validate/matchers.spec.mjs
- tools/schema/restrictions.mjs
- types/restrictions.d.ts
- adds `via` and `viaNot` attributes to rules so you can use them in conjunction with rules that flag circular dependencies
E.g.
```javascript
// log an error for all circular dependencies except when they are via one of the barrels
{
name: 'no-circular',
severity:  'error',
from: {
},
to: {
circular: true,
viaNot: [
'^(app/javascript/tables/index.ts)',
'^(app/javascript/ui/index.tsx)',
]
}
},
// for circular dependencies that pass through one of the barrels generate a warning
{
name: 'no-circular (exception for known barrels)',
severity: 'warn',
from: {
},
to: {
circular: true,
via: [
'^(app/javascript/tables/index.ts)',
'^(app/javascript/ui/index.tsx)',
]
}
}
```
fixes #505 
- The contribution …
> feature(validate): adds via restrictions for cycles

- doc/faq.md
- package.json
- src/extract/transpile/jsx-implementation-rationale.md
- src/extract/transpile/meta.js
- src/extract/transpile/vue-template-wrap.js
- src/meta.js
- test/extract/transpile/meta.spec.mjs
- test/extract/transpile/vue3-template-wrap.spec.js
If you are using Vue3, you might include packages that are incompatible with vue-template-compiler, causing the "isAvailable" function for Vue SFCs to return false. Now, if vue-template-compiler fails to load, we go ahead and try @vue/compiler-sfc as well, in case we have that instead..
Added a different Vue single file component transpiler, following the pattern of what was done with coffeescript modules. 
I want to use dependency-cruiser with my project that includes Vue3 files, but when it checks for available transpilers, `require`ing "vue-template-compiler" errors out because of incompatibility. I added a compatible Vue 3 single file component transpiler that is used if the first one doesn't work.
All existing Vue unit tests still pass. I've also added a new test file, …
> Adding Vue3 @vue/compiler-sfc support

- src/extract/utl/get-extension.js
- test/extract/utl/get-extension.spec.mjs
- types/baseline-violations.d.ts
- types/cruise-result.d.ts
- types/rule-summary.d.ts
- types/violations.d.ts
This fixes the following bug:
> ### Steps taken
> - take 2 .d.ts modules where the one includes the other (one.d.ts => two.d.ts)
> - set the options.enhancedResolveOptions.extensions to [".d.ts"] (so DONOT include ".ts")
> - cruise
> 
> ### Expected
> two.d.ts is a dependency of one.d.ts
> two.d.ts' 'followable' attribute equals true
> 
> ### Found
> two.d.ts is a dependency of one.d.ts (OK)
> two.d.ts' 'followable' attribute equals false (KO)
> 
> ### Background
> 
> Before this bugfix the code determining whether an extension was followable looked
> at the extensions array and compared them with the path.extname (except for .coffee.md
> which is simmilarly weird). As ".ts" !== ".d.ts" followable
> 
> A ripple effect was that .d.ts dependencies were 'completed' into the module graph as
> …
> bugfix(extract): consistently treat .d.ts as a separate extension (BREAKING CHANGE)

- src/enrich/derive/utl.js
Improves performance/ eases code understandability.
On each call to findModuleByName
- it gets the module from the (memoize) cache. If it's not in the cache yet ....
- ... the module is searched with a linear search (Array.find - which is O(N))
This means a lot of O(N) calls before the memoize cache is filled.
- The modulegraph gets cached on the first call (which is O(N))
- All subsequent lookups come from the cache (currently a map with the module name as index)
This should in theory be faster, especially for seriously large dependency-graphs with a memory footprint comparable to the situation before this PR (memoize builds a cache as well and in the end of the run is comparably large as the cache built on the first call).
Just non-regression, surprisingingly. Probably need to run the …
> perf(enrich): use different caching strategy for finding modules by name

- src/schema/configuration.schema.js
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.js
- src/schema/cruise-result.schema.json
- tools/schema/options.mjs
- types/options.d.ts
> bugfix(schema|types): adds metrics flag to options schema

- src/enrich/derive/metrics/folder.js
- src/enrich/derive/metrics/get-stability-metrics.js
- src/enrich/derive/metrics/module.js
- src/enrich/derive/metrics/utl.js
- src/main/options/normalize.js
- test/enrich/derive/metrics/folder.spec.mjs
- test/enrich/derive/metrics/utl.spec.mjs
Puts normalization where it belongs - freeing all other code from having to do the same
> refactor: normalize 'options.metrics' in the normalization step instead of down the line

- .dependency-cruiser-known-violations.json
- .dependency-cruiser.json
- configs/.dependency-cruiser-show-metrics-config.json
- doc/rules-reference.md
- package.json
- src/enrich/derive/metrics/module.js
- src/enrich/enrich-modules.js
- src/main/options/normalize.js
- src/schema/configuration.schema.js
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.js
- src/schema/cruise-result.schema.json
- src/validate/match-dependency-rule.js
- src/validate/matchers.js
- test/enrich/derive/metrics/module.spec.mjs
- test/validate/fixtures/rules.stable-dependencies-only-allowed.json
- test/validate/fixtures/rules.stable-dependencies-only-forbidden.json
- test/validate/index.spec.mjs
- tools/schema/restrictions.mjs
- types/restrictions.d.ts
- adds a moreUnstable boolean attribute to violations
- the presence this attribute will imply dependency-cruiser calculates instability metrics (so there's no need to pass --metrics on the cli or metrics:true in the api)
Enables enforcing the SDP (stable dependencies principle) & highlighting any violations of the principle - as announced in #523. See documentation within the commit for details.
With the earlier PR that adapts the dot reporter you can see what dependencies violate the principle and you can verify why so:
- The contribution is my own …
> feature(validate): adds moreUnstable attribute to enforce stable dependencies

- src/schema/cruise-result.schema.js
- src/schema/cruise-result.schema.json
- test/main/fixtures/cruise-reporterless/metrics.json
- test/main/fixtures/cruise-reporterless/metrics/format-output/index.js
- test/main/fixtures/cruise-reporterless/metrics/mangle-entry/do-something-else.js
- test/main/fixtures/cruise-reporterless/metrics/mangle-entry/do-something.js
- test/main/fixtures/cruise-reporterless/metrics/mangle-entry/index.js
- test/main/fixtures/cruise-reporterless/metrics/parse-input/index.js
- test/main/fixtures/cruise-reporterless/metrics/root.js
- test/main/main.cruise-reporterless.spec.mjs
- tools/schema/dependencies.mjs
- types/cruise-result.d.ts
- see title
- they were missing
> bugfix(schema|types): adds denormalized 'instability' to the schema & types

- src/report/dot/module-utl.js
- src/report/error.js
- src/report/teamcity.js
- src/report/utl/index.js
- test/report/teamcity/mocks/circular-deps.mjs
- test/report/teamcity/mocks/instabilities-teamcity-format.txt
- test/report/teamcity/mocks/instabilities.mjs
- test/report/teamcity/mocks/module-errors.mjs
- test/report/teamcity/mocks/required-errors.mjs
- test/report/teamcity/mocks/unsupported-severity.mjs
- test/report/teamcity/mocks/via-deps.mjs
- test/report/teamcity/teamcity.spec.mjs
- adds instability metrics to the teamcity reporter (in case there was a violation of a rule with moreUnstable in it)
- refactors the teamcity reporter to be more easy to extend
Follow up to adding metrics to dependency-cruiser (issue #523)
> feature(report): adds instability metrics to the teamcity reporter

- src/enrich/summarize/summarize-options.js
- src/main/report-wrap.js
- test/main/main.format.spec.mjs
ℹ️  this is a fix for a bug introduced in code that wasn't released yet. 
After the merge of PR #554 (90c140a9),  depcruise-fmt ignored any filters, collapse patterns, reporter options etc that were part of that cruise result. This PR ...
- ... adds an e2e test that checks for this regression
- ... fixes the bug
> bugfix(main): in report-wrap retain any options already in the summary

- src/extract/utl/extract-module-attributes.js
- test/extract/utl/extract-module-attributes.spec.mjs
makes esm url matching more specific so non-protocol prefixed strings get returned _as is_. 
See the included UT for specifics.
fixes #567 
> bugfix(extract): makes esm url matching more specific

- doc/faq.md
Just some minor changes to replace the href in anchor.
replace to href
> fix(readme): anchor in readme

- configs/.dependency-cruiser-show-metrics-config.json
- src/main/options/normalize.js
- src/validate/match-folder-dependency-rule.js
- test/validate/match-folder-rule.spec.mjs
- adds the possibility to write rules that validate against cycles between folders
Not in scope of this PR: adaptions to reporters to show them, even though the err, err-html and err-long reporters will report them out of the box (just not yet with extended info).
fixes #324 
> feature(validate): adds possibility to define rules to validate against folder cycles

- src/enrich/summarize/index.js
- src/enrich/summarize/summarize-folders.js
- test/enrich/summarize-folders.spec.mjs
- ensures that in text reporters (err, err-long, err-html, teamcity) next to the cycle violation the cycle itself appears.
- also incorporate folder level violations into the violation sorting
- makes it easier to see what the offending cycles are
- the ordering helps prioritise easier
```
##teamcity[inspectionType id='no-folder-cycles' name='no-folder-cycles' description='This folder is part of a circular relationship. You might want to refactor that a bit.' category='dependency-cruiser' flowId='6411767984' timestamp='2022-04-10T11:32:16.622']
##teamcity[inspectionType id='ignored-known-violations' name='ignored-known-violations' description='some dependency violations were ignored; run without --ignore-known to see them' category='dependency-cruiser' flowId='6411767984' …
```
> feature(report): show folder cycles in textual reporters

- doc/cli.md
- src/cli/tools/svg-in-html-snippets/script.snippet.js
Adds this behaviour to dependency graph visualisations:
- A left mouse click ('on context menu) 'pins' the highlighted modules and dependencies, so when your mouse moves away from them they're still highlighted.
- A left-click on something that isn't a module or dependency clears the highlight again. A press on the  _Escape_ key does the same.
Highlight-on-hover has proven useful, but when you want to trace a dependency in a large graph it's often hard to keep track as you'd need to keep hovering the same dependency. The ability to 'pin' makes it easier to keep track.
- The contribution will be subject to [The MIT license](https://github.com/sverweij/dependency-cruiser/blob/develop/LICENSE), and …
> feature(wrap-stream-in-html): adds ability to 'pin' a highlight with a left mouse click

- src/cli/tools/svg-in-html-snippets/header.snippet.html
- src/cli/tools/svg-in-html-snippets/script.snippet.js
- src/cli/tools/wrap-stream-in-html.js
- adds a small screen with some hints on how to use the graph
- adds a button on the top right that toggles the visibility of that screen
- binds F1 to toggle that screen as well
- binds ESC to also close that screen
The new 'left click to pin' feature isn't as discoverable as 'highlight-on-hover'. Goal of this PR is to improve its discoverability (hopefully as unobtrusively as possible).
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/develop/.github/CONTR …
> feature(wrap-stream-in-html): adds simple help system

- doc/rules-reference.md
- src/validate/match-folder-dependency-rule.js
- test/validate/match-folder-dependency-rule.spec.mjs
-  adds group matching to folder scoped rules
- provides symmetry with the path & pathNot rules in module scope
- might be helpful with the use case as sketched in #585 
> feature(validate): adds group matching to folder scoped rules

- src/extract/get-dependencies.js
- test/backwards.utl.mjs
- test/extract/__fixtures__/ts-types.json
- test/extract/__mocks__/ts-types/things.ts
- test/extract/__mocks__/ts-types/two-import-types-one-dependency-one-import-statement.ts
- test/extract/__mocks__/ts-types/two-import-types-one-dependency.ts
- test/extract/get-dependencies.ts-types.spec.mjs
- if there's a type import _and_ a regular import of the same module in the same file dependency-cruiser now treats these as two separate dependencies
```typescript
// two-import-types-one-dependency.ts
import { otherThing } from "./things";
import type { IThing } from "./things";
```
```typescript
// things.ts
export interface IThing {
id: number;
thing: string;
}
export const otherThing = 481;
```
run something like this:
```
npx dependency-cruise --ts-pre-compilation-deps two-import-types-one-dependency.ts -T json 
```
result:
<details>
```javascript
//..
{
"source": "two-import-types-one-dependency.ts",
"dependencies": [
{
"dynamic": false,
"module": "./things",
"moduleSystem": "es6",
"exoticallyRequired": false,
"resolved": "things.ts",
"coreModule": false,
"followable": true, …
```
> feature(extract): makes an type import and an import of the same module in the same file two separate dependencies

- doc/options-reference.md
- src/main/options/defaults.js
- src/main/options/normalize.js
- test/cli/__fixtures__/babel/babel-es6-result.json
- test/cli/__fixtures__/babel/babel-ts-result.json
- test/cli/__fixtures__/cjs.dir.filtered.json
- test/cli/__fixtures__/cjs.dir.json
- test/cli/__fixtures__/cjs.file.json
- test/cli/__fixtures__/dynamic-import-nok.json
- test/cli/__fixtures__/dynamic-import-ok.json
- test/cli/__fixtures__/multiple-in-one-go.json
- test/cli/__fixtures__/typescript-path-resolution.json
- test/cli/__fixtures__/webpack-config-alias-cruiser-config.json
- test/cli/__fixtures__/webpack-config-alias.json
- test/main/__fixtures__/jsx-as-object.json
- test/main/__fixtures__/jsx.json
- test/main/__fixtures__/ts-no-precomp-cjs.json
- test/main/__fixtures__/ts-no-precomp-es.json
- test/main/__fixtures__/ts-precomp-cjs.json
- test/main/__fixtures__/ts-precomp-es.json
- test/main/__fixtures__/ts.json
- test/main/__fixtures__/tsx.json
- test/main/__mocks__/collapse-after-cruise/expected-result.json
- test/main/__mocks__/dynamic-imports/es/output.json
- test/main/__mocks__/dynamic-imports/typescript/output-pre-compilation-deps.json
- test/main/__mocks__/dynamic-imports/typescript/output.json
- test/main/__mocks__/type-only-imports/output-with-rules.json
- test/main/__mocks__/type-only-imports/output.json
- test/main/__mocks__/type-only-module-references/output-no-ts.json
- test/main/__mocks__/type-only-module-references/output.json
- moduleSystems passed on cli or as options were sorted before they went into any processing. This is slightly unexpected and not necessary.
> bugfix(main): don't sort the moduleSystems passed as options; change default order from most used to least used

- src/main/utl/normalize-re-properties.js
- test/validate/index.cycle-via-not.spec.mjs
- test/validate/index.cycle-via.spec.mjs
An array of strings (string-as-regex'es) passed to `viaOnly` and `viaSomeNot` weren't processed the same as the ones for e.g. `path` were. This PR corrects that, so that feature can also be used for these restrictions
> bugfix(main): also normalize viaOnly and viaSomeNot

- src/main/rule-set/validate.js
`via`, `viaNot`, `viaOnly` and `viaSomeNot` hitherto were not checked for regular expression safety like e.g. the `path` and `license` fields do. This will prevent abnormally long running rules on your local machine and your CI's.
> bugfix(main): also check via's for regex safety

- doc/rules-reference.md
- src/validate/matchers.js
- test/validate/index.cycle-via-not.spec.mjs
- test/validate/index.cycle-via-some-not.spec.mjs
- test/validate/index.cycle-via.spec.mjs
Version 11.7.0 started to not consider the 'from' in 'via' like exceptions to cycle rules. This was not only breaking, but also incorrect .
fixes #604
> bugfix(validate): also include the 'from' when validating via's/ & viaNot exceptions to cycle rules

- bin/depcruise-fmt.js
- doc/cli.md
- src/cli/format.js
- test/cli/format.spec.mjs
- types/options.d.ts
- adds a `--prefix` option to the depcruise-fmt command that works the same as the one in the depcruise command
So there's no need to recalculate all dependencies just to add a different prefix to a report
> feature(depcruise-fmt): adds a --prefix command line option

- src/extract/gather-initial-sources.js
- we still used `.endsWith` to determine scanability of an extension, while we have a specialised central utl for it
> refactor(extract): use getExtension instead of endsWith to determine scannability of extensions

- doc/options-reference.md
- doc/rules-reference.md
> doc: clarify when the showMetrics dot reporter attribute works and when it doesn't

- configs/plugins/mermaid-reporter-plugin.js
- package.json
- test/configs/plugins/mermaid-reporter-plugin/module-level/__mocks__/with-focus.json
- test/configs/plugins/mermaid-reporter-plugin/module-level/__mocks__/with-focus.mmd
- test/configs/plugins/mermaid-reporter-plugin/module-level/index.spec.mjs
- adds focus highlighting to the mermaid reporter;
Also includes the mermaid reporter plugin along with the regular test coverage (it was already 100% covered to start with - and we don't want that to grow less ;-) )
@MH4GF has been working on a _very nice_ [GitHub action](https://github.com/MH4GF/dependency-cruiser-report-action) that can add a mermaid report to
your pull request that shows the modules the PR is about. It'd be awesome if they could expand a bit to not only show the modules touched by the PR, but _also_ the immediate context. This is what dependency-cruiser's (existing) focus feature is for. 
In the context of a PR it'd however be useful to see which modules are the ones _touched_ by the PR and which are included in the model for _context_ only. This PR adjusts that.
> …
> feature(mermaid-plugin): adds focus highlighting

- doc/options-reference.md
- src/main/options/normalize.js
- test/main/options/normalize.cruise-options.spec.mjs
- calculate metrics when the current reporter's option specifies to show them
It's non-obvious when `showMetrics === true` for a reporter but they don't show up. The original reason for this behaviour was to prevent unexpected performance hits. However, when you set showMetrics to true in a reporter you either take that for granted or don't care either way.
Fixes #610 
> feature(metrics): calculate metrics when the current reporter's option specifies to show them

- src/report/mermaid.js
- test/report/mermaid/mermaid.spec.mjs
- types/reporter-options.d.ts
Some things I forget to add (/ didn't notice in the PR review):
* bugfix(types): make mermaid optional in options type
* bugfix(test|mermaid): adds scenario where no options are passed to the reporter
* refactor(test|mermaid): dedupe comparison function
* refactor(mermaid): use .has instead of .get to test whether a key is in the hash map
* style(mermaid): apply some code style rules that don't have an automated check on them yet
* these are things that don't matter for the functioning of the code, but do
make it look a bit more familiar to the code style of the rest of the code base.
As long as there's no automated check (or even better: automatic fix) on them
I'm not comfortable to put these as review comments.
* Replaces arrow function expressions with a regular named `function` where …
> bugfix(mermaid): small fixes to types, tests

- src/enrich/summarize/summarize-options.js
- test/enrich/summarize.spec.mjs
- removes 'progress' from shareable options
- adds a schema check to the summarisation unit tests
- it's not properly normalised, as it turns out - so sharing it as is violates the json schema.
- progress isn't super important to reproducing the same results anyway
> bugfix(enrich): removes 'progress' from shareable options in options summary

- package.json
- src/cli/init-config/get-user-input.js
- replaces the interactive prompt dependency 'inquirer' with 'prompts'
- the newer version of inquirer is ESM only, which means we can't use it until the moment we are as well (this might happen in the future, but 
- I've selected 'prompts' because:
- prompts is used about as much as inquirer (which is _a lot_ - 17M per week vs 23M)
- prompts has a relatively small footprint (inquirer a.o. drags in rxjs which is a 10Mb+ node module, prompts has two very small dependencies)
- has all features we need (inquirer likely has more features, but those we don't use)
- its usage in the code is testable whereas last time I checked inquirer this wasn't possible with inquirer
- migration from inquirer to prompts is trivial
- I've selected 'prompts' in spite of:
- sparse updates (last update was 9 …
> refactor(init): replaces 'inquirer' with 'prompts'

- doc/options-reference.md
- package.json
- src/cli/init-config/environment-helpers.js
- src/config-utl/extract-webpack-resolve-config.js
- test/config-utl/__mocks__/webpackconfig/webpack.config.json5
- test/config-utl/__mocks__/webpackconfig/webpack.config.mjs
- test/config-utl/__mocks__/webpackconfig/webpack.config.unknown-extension
- test/config-utl/extract-webpack-resolve-config.spec.cjs
- adds support for (a.o.) webpack configs written in typescript using [rechoir](https://github.com/gulpjs/rechoir) and [interpret](https://github.com/gulpjs/interpret)- which is what webpack-cli also uses.
- ensures the --init scaffolding also recognises these variants (or at least the most common ones).
> Versions of dependency-cruiser that include the changes in this PR are published as a betas on npm:
> `dependency-cruiser@11.15.0-beta-1`; shasum: `86b52f3ae600a5f4923d202ae7190940260d2e4f`
> (which doesn't have rechoir & interpret as dependencies)
> `dependency-cruiser@11.15.0-beta-1`; shasum: `8b3f3f448047db0fcf843bbb9018726c663f1b32`
> (which _does_ have them as regular dependencies)
~It makes use of _already available_ versions of _rechoir_ and _interpret_, so users will have to …
> feature(config-utl): enable support of more types of webpack.conf (typescript, json5, yaml etc)

- README.md
Triggered by #657 it seems the README could use a bit of a refresher. This PR:
- ... restructures the copy so it's easier to do the right thing ™️:
- run --init
- use a .dependency-cruiser.js
- run as a local devDependency
- ... removes any reference to running dependency-cruiser as a global command (this remains possible, but is only useful for repo's that don't contain aliases or for environments that either use vanilla JavaScript or have compilers globally installed - both of which seem dying breeds).
- ... introduces the use of `npx` which will make it harder to copy paste and get errors.
- ... adds a footnote with the download link for GraphViz' dot
- The contribution will be subject to [The …
> doc(README): restructures 'how do I use it' section

- src/main/options/validate.js
- src/main/rule-set/validate.js
- relaxes the safe-regex check on repeats within regular expressions that are used within rule sets
See the comment added to src/main/rule-set/validate.js for details on the implementation.
Published on npm as `dependency-cruiser-11.16.0-beta-1`, shasum: `ff83cf05411f7d11d465de7143c82d02ef149b17`
fixes #651
> feature(validate): relaxes safe-regex check on on repeats within rule sets

- src/main/options/normalize.js
- src/main/rule-set/normalize.js
- src/main/rule-set/validate.js
- src/main/utl/normalize-re-properties.js
- test/main/rule-set/validate.spec.mjs
- test/main/utl/normalize-re-properties.spec.mjs
- test/validate/__mocks__/rules.ok-regex-just-repeating.json
- test/validate/__mocks__/rules.scary-regex-array.json
When checking passed paths in rules for regular expression safety, if they were arrays we passed them as such - in stead  of first normalising them to  regular-expression-as-a-string. For safe-regex it didn't seem to matter in its current implementation, but we shouldn't rely on such implementation details.
fixes #651 (second part)
> bugfix(validate): don't pass arrays to safe-regex

- .github/dependabot.yml
see title
- npm deps are kept up to date already (semi-automated)
- GitHub actions dependencies weren't, though - this PR changes this.
> chore(ci): configures dependabot for keeping github actions dependencies up to date

- .dependency-cruiser-known-violations.json
- configs/plugins/mermaid-reporter-plugin.js
- package.json
- test/report/mermaid/mermaid.spec.mjs
Just a reference to the internal reporter works just as well as the previous construct (that just re-exported the internal reporter) + it's simpler & uses no code.
> refactor(plugins): simplify construct to expose mermaid plugin and stay backword compatible

- configs/.dependency-cruiser-unlimited.json
- package.json
- src/cli/init-config/config.js.template.hbs
- src/extract/ast-extractors/swc-dependency-visitor.js
- src/extract/resolve/index.js
- src/extract/transpile/meta.js
- src/extract/transpile/typescript-wrap.js
- test/extract/transpile/__fixtures__/mts.mjs
- test/extract/transpile/__mocks__/mts.mts
- test/extract/transpile/meta.spec.mjs
- test/extract/transpile/typescript-wrap.spec.mjs
- adds .cts and .mts to the supported extensions and instructs the typescript compiler to properly handle .mts (.cts is already handled as it's same as a .ts)
- ensures the weird file resolution (ends in .js? could be the .ts you meant) for typescript also extends to .cts and .mts extensions.
- to ease analysis of files impacted by this PR: adds a config & updates the depcruise:reaches package.json run script to show locally what is impacted on _all_ files, even in test.
- documents the `extensions` option in the template for .dependency-cruiser.js files - the more extensions in there the slower enhanced-resolve will resolve in worst case scenario situations - documenting that will hopefully make it easier to figure out how to tune dependency-cruiser to their environment.
- 🏕️ corrects an …
> feature(extract): adds support for TypeScript 4.7 .cts and .mts extensions

- bin/depcruise-fmt.js
- doc/cli.md
- src/cli/format.js
- src/main/options/normalize.js
- adds a `--highlight` option to the decpruise-fmt cli interface (see #675)
Consistency.
see #675 
> feature: adds 'highlight' option to depcruise-fmt as well

- src/cli/format.js
- src/cli/normalize-cli-options.js
- removes the scrubbing of unknown options from the cli (both depcruise-fmt.js and dependency-cruise.js)
These days commander already delivers just the passed  options and nothing more, so it's  not necessary anymore to do this. 
> refactor(cli): removes cli option scrubbing

- src/report/dot/module-utl.js
- src/report/error-html/utl.js
- src/report/error.js
- src/report/teamcity.js
- test/report/dot/module-utl.spec.mjs
- test/report/error-html/utl.spec.mjs
- test/report/error/error.spec.mjs
- test/report/markdown/markdown.spec.mjs
- test/report/teamcity/__mocks__/instabilities-teamcity-format.txt
- Adds a `%` sign to metrics in those reporters that emit them as a value from 0-100 instead of from 0.0 - 1.0:
- `dot` (and with that all dot-derived ones)
- `error-html`
- `err`, `err-long`
- `markdown`
- `teamcity`
- Updates the unit test expectations for these reporters to match that.
We use values between 0 and 100 for readability reasons, whereas the original stability metrics were defined as values between 0 and 1. Adding a % sign next to these numbers will clarify that difference.
Addresses #683
- I …
> fix(report): adds a percentage sign to reporters that emit stability metrics

- src/report/metrics.js
- test/report/metrics/metrics.spec.mjs
- makes the `metrics` reporter emit the Instability metric as a percentage
- adapts the unit test's expectation to account for this change
... so it's (1) more readable (2) consistent with all other reporters that show the instability metric
> bugfix(report): shows the instability metric as percentage in the metrics reporter as well

- doc/assets/theming/base.svg
- doc/real-world-samples/dependency-cruiser-dir-graph.svg
- doc/real-world-samples/dependency-cruiser-without-node_modules.svg
- docs/assets/berry-high-level-dependencies.html
- docs/assets/react-high-level-dependencies.html
- docs/dependency-cruiser-archi-graph.html
- docs/dependency-cruiser-dependency-graph.html
- docs/dependency-cruiser-dir-graph.html
- docs/schema-overview.html
- src/cli/tools/svg-in-html-snippets/header.snippet.html
Just changed the references of Left-Click to right click about pinning dependency graphs
From my experience, Left-Click is to follow the dependency to a remote place (like github or the filesystem)
> fix: right-click is the correct for pin in UI

- src/enrich/summarize/summarize-options.js
- test/cli/__fixtures__/alternate-basedir/expected.json
- test/cli/asserthelpers.utl.mjs
- test/cli/index.spec.mjs
- test/main/__fixtures__/ts-no-precomp-cjs.json
- test/main/__fixtures__/ts-no-precomp-es.json
- test/main/__mocks__/dynamic-imports/es/output.json
- test/main/__mocks__/dynamic-imports/typescript/output-pre-compilation-deps.json
- test/main/__mocks__/dynamic-imports/typescript/output.json
- test/main/__mocks__/type-only-imports/output-with-rules.json
- test/main/__mocks__/type-only-imports/output.json
- test/main/__mocks__/type-only-module-references/output-no-ts.json
- test/main/__mocks__/type-only-module-references/output.json
- test/main/main.cruise.dynamic-imports.spec.mjs
- test/main/main.cruise.spec.mjs
- test/main/main.cruise.ts-pre-compilation-deps.spec.mjs
- test/main/main.cruise.type-only-imports.spec.mjs
- test/main/main.cruise.type-only-module-references.spec.mjs
- test/main/norm-base-directory.utl.mjs
- adds the used `baseDir` in to the optionsUsed object in the output json
- adapts any automated test that didn't expect it to expect it
- will help with debugging and with creating more rich reporters
> feature(summarize): adds the 'baseDir' option to the optionsUsed object in the summary

- doc/cli.md
- src/cli/listeners/performance-log/format-helpers.js
- src/cli/listeners/performance-log/handlers.js
- test/cli/listeners/performance-log-listener/format-helpers.spec.mjs
- adds _resident set size_ (rss) and the amount of C++ objects bound to javascript objects managed by v8 ('external') to the `performance-log` output.
- provides more (useful) information to analyze what dependency-cruiser is doing under the hood.
```
$ node ./bin/dependency-cruise.js src bin test configs types tools --config --ignore-known
elapsed       rss heapTotal  heapUsed  external after step...
751ms     127Mb      84Mb      61Mb       2Mb start of node process
11ms     128Mb      84Mb      62Mb       2Mb parsing options
93ms     130Mb      85Mb      63Mb       2Mb cache: checking freshness
...
```
```
$ node ./bin/dependency-cruise.js src bin test configs types tools --config --ignore-known
elapsed heapTotal  heapUsed after step...
751ms      84Mb      61Mb start of node process …
```
> feature(progress): adds resident set size & v8 managed memory to the performance-log

- src/report/dot/module-utl.js
- src/report/error-html/utl.js
- src/report/error.js
- src/report/metrics.js
- src/report/teamcity.js
- src/report/utl/index.js
- test/report/metrics/metrics.spec.mjs
- replaces the instability metrics formatting code with an Intl function call
- reduces maintenance
- output is localized, so at least in theory easier to grasp for the reader
> refactor(report): replaces metrics formatting code with Intl API calls

- .eslintrc.json
- src/cli/index.js
- src/config-utl/extract-depcruise-config/index.js
- src/config-utl/extract-webpack-resolve-config.js
- src/enrich/derive/circular/get-cycle.js
- src/extract/ast-extractors/swc-dependency-visitor.js
- src/extract/get-dependencies.js
- src/extract/resolve/determine-dependency-types.js
- src/report/markdown.js
- src/report/mermaid.js
- test/extract/transpile/svelte-preprocess.spec.mjs
- removes the last parameter reassignments from the code
- makes the concerned code easier to understand + less easy to introduce subtle bugs
> refactor: bans parameter reassignments

- .husky/pre-commit
- package.json
- upgrades lint-staged to latest
This was an issue because later versions than the one we were using borked with 'invalid json' errors. Turns out newer versions of lint-staged autodiscovered their way to all possible configuration files that can be in a repository. This included package.json's in our test tree that are deliberately invalid. The way to stop this autodiscovery to make the one configuration file explicit (add a --config parameter in the lint-staged call in .husky/pre-commit).
Chore/ LCM
- I am …
> chore: upgrades lint staged

- package.json
- test/config-utl/extract-webpack-resolve-config.spec.cjs
- upgrades `interpret` to ^3.1.0 - so it's the same as webpack-cli's version
- LCM
> chore: upgrades 'interpret' to stay in line with what webpack-cli uses

- src/cli/format.js
- src/cli/index.js
- src/cli/init-config/index.js
- src/config-utl/extract-depcruise-config/read-config.js
- src/config-utl/make-absolute.js
- src/enrich/add-validations.js
- src/enrich/derive/orphan/index.js
- src/enrich/derive/orphan/is-orphan.js
- src/enrich/derive/reachable/index.js
- src/graph-utl/consolidate-module-dependencies.js
- src/graph-utl/consolidate-modules.js
- src/graph-utl/consolidate-to-folder.js
- src/report/baseline.js
- src/report/csv.js
- src/report/dot/index.js
- src/report/dot/prepare-custom-level.js
- src/report/dot/prepare-flat-level.js
- src/report/dot/prepare-folder-level.js
- src/report/error-html/index.js
- src/report/error.js
- src/report/html/index.js
- src/report/identity.js
- src/report/json.js
- src/report/markdown.js
- src/report/mermaid.js
- src/report/metrics.js
- src/report/teamcity.js
- src/report/text.js
- src/report/utl/dependency-to-incidence-transformer.js
- replaces all anonymous functions that were assigned to a `module.exports`
Non-anonmous functions are easier to identify in heap and cpu profiles
> refactor: reduces anonymous top level functions

- package.json
- src/report/mermaid.js
- test/report/mermaid/__mocks__/collapsed.json
- test/report/mermaid/__mocks__/collapsed.min.mmd
- test/report/mermaid/mermaid.spec.mjs
- if a node has no name, label it `" "` in stead of `""` the latter of which mermaid refuses to render
These nodes occur when running dependency-cruiser with a `--collapse` pattern. This is a temporary band-aid until we've found a way to have the mermaid reporter output these more elegantly.
coming up
> bugfix(mermaid): makes nodes without a name render as well

- package.json
- src/cli/init-config/build-config.js
- src/cli/init-config/environment-helpers.js
- src/cli/init-config/get-user-input.js
- src/cli/init-config/index.js
- src/cli/init-config/validators.js
- src/cli/init-config/write-config.js
- test/cli/init-config/validators.spec.mjs
- types/init-config.d.ts
- renames the inquirers-validators.js to validators.js (we're not using inquirer anymore and for the validators it's not relevant in any case
- removes a function in that file that wasn't used (other than in a test - which got removed too)
- corrects spelling of some functions & variable names
- corrects/ clarifies some typings in the init-config code (it's not perfect yet, but better than it was)
- removes attributes from IInitOptions interface as they weren't used anymore + added the jsConfig ones 
- should ease maintenance a bit
- dead code will rot ...
- The contribution will be subject to [The MIT license](https://github.com/sverweij/dependency-cruiser/blob/develop/LICENSE), and I'm OK with …
> refactor(init-config): removes superfluous function; touches up the typing a bit

- src/report/metrics.js
- test/report/metrics/metrics.spec.mjs
- reserves an extra character of room for displaying metrics in the metrics reporter
- also removes a superfluous `toString` statement from the same
Some locales put a space between the number and the percentage sign. The max width of the I column didn't account for that - resulting in misalignment between 3 and < 3 number percentages:
```
100 %
90 %
1 %
100 %
```
After the fix it looks normal in these locales again:
```
100 %
90 %
1 %
100 %
``` …
> bugfix(report): improves instability alignment in metrics reporter

- src/cli/listeners/performance-log/format-helpers.js
- test/cli/listeners/performance-log-listener/format-helpers.spec.mjs
- uses `+` & `concats` in stead of template strings to improve readability of the code that produces the performance logs
Improves readability & maintainability of the code.
> refactor(performance-log): improves readability of code

- src/report/mermaid.js
- test/report/mermaid/__mocks__/dependency-cruiser-2019-01-14.min.mmd
- test/report/mermaid/__mocks__/with-focus.min.mmd
- makes the 'minified' node names in generated mermaid uppercase
There's some interesting edge cases in the mermaid flowchart language. These two seemingly equal flowcharts render differently. Reason is that `o-->` is an arrow shape. Two ways to fix it
- use spaces (`o --> a`) -> this would make the generated .mmd larger, so we'll bump into mermaid's maximum input limit faster
- don't use the characters that manifest the ambiguity (`o` and `x`). Easiest way to accomplish that is to uppercase the 'minified' node names.
```
flowchart LR
o
a
o-->a
```
```mermaid
flowchart LR
o
a
o-->a
```
```
flowchart LR
O
A
O-->A
```
```mermaid
flowchart LR
O
A
O-->A
```
- The contribution will be subject to [The …
> bugfix(mermaid): circumvents mermaid edge naming ambiguities

- src/cache/options-compatible.js
- src/cache/utl.js
- test/cache/cache.spec.mjs
- test/cache/options-compatible.spec.mjs
- adds a cache option compatibility check to the check whether options are compatible as different cache strategies will yield different outcomes no matter what.
- 🏕️ also swaps out  assert.deepEqual with assert.deepStrictEqual as the former is deprecated in favor of the latter.
> feature(cache): adds a cache option compatibility check

- .dependency-cruiser.json
- .gitignore
- package.json
- src/cli/init-config/find-extensions.js
- src/cli/init-config/normalize-init-options.js
- src/utl/find-all-files.js
- test/cli/init-config/find-extensions.spec.mjs
- test/cli/init-config/normalize-init-options.spec.mjs
- separates the part that 'finds all files' for the init functionality to utl
- enable the 'find all files' functionality to respect the local `.gitignore`
I don't yet like the spot we read the .gitignore; probably going to bubble that up sooner or later (maybe even as part of this PR).
- We'll be needing the same 'find all files' functionality as well as the .gitignore functionality to implement the thing for #715.
- It's better of being its own responsible little unit in any case …
> refactor(init): separates 'find all files' functionality & make it respect .gitignore

- src/cache/cache.js
- src/cache/git-revision-data.js
- src/cache/options-compatible.js
- src/cache/utl.js
- uses util.isDeepStrictEqual for checking deep equality. Should've used that in the first place (it's used elsewhere in the code base as well ...).
- camping site rule: removes cache reset from cache.writeCache (not its responsibility + it's happening in the right spot already anyway)
> refactor(cache): uses util/isDeepStictEqual instead of its assert variant

- src/cli/normalize-cli-options.js
- changes logic in the cli options normalization step to early returns
I think now that this makes for code that is easier to read
> refactor(cli): changes normalize steps to early returns

- bin/dependency-cruise.js
- src/cli/normalize-cli-options.js
- test/cli/normalize-cli-options.spec.mjs
- adds a --cache-strategy option to select the cache strategy from the cli
Likely to be more practical when you want to keep the same configuration, but only need to switch the strategy based on the environment you're on (e.g. on the CI). 
> feature(cli): adds --cache-strategy option

- src/cache/utl.js
- test/cache/find-content-changes.spec.mjs
The list of 'changes' contains files/  modules dependency-cruiser was not  able to 'follow' (e.g.  because it's an unsupported file type) with changeType _deleted_  - e.g. css or  picture  imports in react projects. Apart from that these entries are  superfluous and make the list larger than necessary, this caused the second run  without any changes to not use the cache.
> A beta  version of dependency-cruiser that includes the fix in this  PR has been published on npmjs:
> - `dependency-cruiser@12.5.1-beta-1`        
> - sha-sum: `c294e758a9dcd5828ebcdd2742c53fd7cd5948f3`
Fixes a bug @7rulnik found  while validating #715 (thanks!)
- The contribution will be subject to [The MIT …
> bugfix(cache): ignores unfollowables in content cache strategy

- doc/cli.md
- src/cli/listeners/performance-log/format-helpers.js
- src/cli/listeners/performance-log/handlers.js
- test/cli/listeners/performance-log-listener/format-helpers.spec.mjs
- test/cli/listeners/performance-log-listener/handlers.spec.mjs
- makes the performance-log listener show all totals (instead of only wall-clock time and heap used totals)
- dedicates a separate line to the totals
- widens the width of all columns to accommodate large numbers in locales that use a bit more room.
The listener already showed ∑ wall-clock time and ∑ heap used. This PR adds the ∑ for all other metrics as well (user & system time spent, rss, heap total, external memory). Also instead of putting it in the free format message text it's now in the same column as their per step ∆'s).
The new representation should be easier to read, while at the same time providing more information to analyze performance bottlenecks.
A typical output now looks like this (de_DE locale):
```
elapsed real          user        system         ∆ rss   ∆ heapTotal …
```
> feature(progress): makes performance-log listener show all totals

- bin/dependency-cruise.js
- doc/cli.md
- adds `--no-cache` command line option
If you want or need to override an earlier set --cache, --cache-strategy cli option or a `cache` option. The functionality is already built into dependency-cruiser, we only didn't include it in the commander definition yet. This PR does just that.
> feature(cli): adds --no-cache option

- README.md
- adds a message to the README
Apparently pnpx (from the pnpm package manager) works different from npx - as noted in #725. 
> doc(README): adds a message about the use with pnpx (/ yarn run)

- bin/dependency-cruise.js
- doc/cli.md
- adds a `--no-progress` option to the command line interface
- corrects a typo in a link in the cli doc
symmetry is a beautifull thing
> feature(cli): adds --no-progress option

- .c8rc.json
- package.json
- moves c8 cli parameters to a separate configuration file
- more readable & easier to maintain
- smaller package.json
When we first started using c8 there wasn't (or didn't seem to be?) an option to put things in a configuration file, so we used the command line parameters.
> chore(test): moves c8 cli parameters to .c8rc.json

- .eslintrc.json
- package.json
- moves eslintignore from package.json into the .eslintrc
- it keeps eslint things in one place, which is easier to maintain
- it reduces the size of the package.json and hence the package we ship
> chore(lint): moves eslintignore from package.json into the .eslintrc

- .husky/pre-commit
- .lintstagedrc.json
- package.json
- moves lintstaged config from package.json to its own file
- which makes package.json a bit smaller
- is more explicit/ easier to find
> chore(ci): moves lintstaged config from package.json to its own file

- src/extract/get-dependencies.js
- test/extract/__fixtures__/ts-types.json
- test/extract/__mocks__/ts-types/two-import-types-one-dependency.mts
- expands the extensions for which swc and tsc are used with .mts and .cts
This way pre-compilation dependencies (unused ones, type-only ones) will be detected in .mts and .cts modules as well + it will be a little bit faster because the typescript => javascript step is skipped.
> bugfix(extract): uses tsc or swc for .mts & .cts as well

- .github/ISSUE_TEMPLATE/use-without-config.md
- bin/dependency-cruise.js
- doc/cli.md
- src/cli/normalize-cli-options.js
- Adds a `--no-config` option
In the future we want dependency-cruiser to pick up configuration files without having to specify one.  That future feature will be a breaking change a.o. because it would be harder to run without a configuration file if there's one available. This option ensures  that that behavior remains available, because, altough dependency-cruiser is most useful when used _with_ a configuration file, it _can_ be used without one and we can't be certain that it isn't used  without one.
- I …
> feature(cli): adds --no-config option

- README.md
> Leave an [issue](https://github.com/sverweij/dependency-cruiser/issues/new/choose) with a
> do that, so we can have a conversation before you start. This will save you time!
Update README.md about how to install
> Update README.md about how to install

- bin/dependency-cruise.js
- doc/cli.md
- hides the following implied options from `--help`:
- `--no-config` (implied by `--config`)
- `--no-progress` (implied by `--progress`)
- `--no-cache` (implied by `--cache`)
- hides `--validate` which is an alias for `--config`
- hides `--max-depth` - which is superseded by the more useful & powerful `--focus`/ `--focus-depth` and `--collapse` options
- lets commander validate of passed values for `--progress` and `--cache-strategy` - which comes with automatic hinting
- lets commander put `"err"` as the default value for the reporter
The `--help` output is becoming  large. Removing implied options and options that have gotten an alias or alternative over time  makes the the output looks less intimidating, and easier to navigate. 
This also means we'll have to _add_ `--no-xxx` options …
> feature(cli): hides depcrated and implied options from --help output

- bin/dependency-cruise.js
- doc/cli.md
- src/cache/options-compatible.js
- src/cli/normalize-cli-options.js
- test/cache/options-compatible.spec.mjs
- adds a `--no-ignore-known` option to the cli (which doesn't show up in --help as it can be considered as implied by the existence of the `--ignore-known` option)
- fixes a bug in the option compatibility check for caching (for non-filter options, if previous option wasn't there, the presence of a new option now correctly implies a dirty cache).
- to remain symmetric with other options that can have a boolean value
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruise …
> feature(cli|cache): adds --no-ignore-known option

- bin/dependency-cruise.js
- doc/cli.md
- adds a `--no-metrics` option to the cli. 
It won't show up in `--help` as it's implied to exist by `--metrics`
Consistency with other semi-boolean command line options
> feature(cli): adds --no-metrics option

- .dependency-cruiser.json
- bin/dependency-cruise.js
- doc/cli.md
- hides the following options in the command line help:
- `--ts-config`
- `--webpack-config`
- `--ts-pre-compilation-deps`
- `--module-systems`
- `--preserve-symlinks`
- adds `ndjson` to the choices possible for the `--progress` option (actually a bugfix)
- adds a link to the full documentation
For the now hidden options it makes more sense to specify them in a .dependency-cruiser.js - they are part of the command line options for backwards compatibility only. Keeping them in the cli help would stimulate sub-optimal use of dependency-cruiser + without them the help text is _much_ shorter.
```
Usage: dependency-cruise [options] [files-or-directories]
Validate and visualize dependencies.
Details: https://github.com/sverweij/dependency-cruiser
Options:
--init [oneshot]               set up …
```
> feature(cli): makes cli help output more focused

- src/extract/ast-extractors/extract-typescript-deps.js
- test/extract/ast-extractors/extract-typescript-type-imports-and-exports.spec.mjs
- adds support for type only re-exports 
```typescript
export type * as vehicles from './vehicles';
export type * from './roads';
```
> - As with other type only stuff, this only works with `tsPreCompilationDeps: true`, or with a 
> TypeScript capable parser.
> - Different from other type only stuff this _does not_ work with the `swc` `parser`, as it looks like `swc` doesn't support this yet. Which is not that weird, as TypeScript has only been out for a few days. When swc starts supports it I'll open a PR for it (unless somebody else does it).
This was added in TypeScript 5 - see [TypeScript 5 release notes]( https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#support-for-export-type)
- it _does_ and I have …
> feature(extract): adds support for TypeScript (>= 5) type only re-exports

- .dependency-cruiser.json
- doc/real-world-samples/react-dependency-cruiser-config.js
- src/cli/init-config/config.js.template.hbs
- test/extract/__mocks__/reachable/.dependency-cruiser.js
- test/integration/yarn-pnp.template/.dependency-cruiser.js
Changed the use of `args` to `arguments` in the config JS file template in the context of the `options.webpackConfig` section.
Our webpack config exports a function that relies on the second parameter to retrieve the `mode` (e.g. `'production'`). So I customized the generated config file to set `options.webpackConfig.args` to `{ mode: 'production' }`. When I attempted to run `dependency-cruiser` using it, I got a `TypeError` about trying to access the `mode` property on a null value. When I logged out the values, I saw that the second value was indeed coming in as null. So I looked in the code to see where it was reading the `webpackConfig` settings and found that the correct property name was `arguments`, not `args`.
So I figured I would update the template that generates the config so …
> Replace "args" with "arguments" in config file template

- doc/api.md
- src/cli/index.mjs
- src/main/index.js
- test/main/main.cruise.cache.spec.mjs
- test/main/main.cruise.dynamic-imports.spec.mjs
- test/main/main.cruise.spec.mjs
- test/main/main.cruise.ts-pre-compilation-deps.spec.mjs
- types/dependency-cruiser.d.ts
- replaces the `cruise` interface with the more generic `futureCruise`
Enables more types of transpiler options to be passed - a thing already in use for babel configuration options. 
Before:
```javascript
import { cruise } from 'dependency-cruiser';
import extractDepcruiseConfig from "dependency-cruiser/config-utl/extract-depcruise-config";
import extractTSConfig from "dependency-cruiser/config-utl/extract-ts-config";
import extractWebpackResolveConfig from "dependency-cruiser/config-utl/extract-webpack-resolve-config"
import extractBabelConfig from "dependency-cruiser/config-utl/extract-babel-config";
const lCruiseOptions = {
// ...
};
const lResult = main.cruise(
["src", "test"],
await extractDepcruiseConfig("./.dependency-cruiser.js"),
extractWebpackResolveConfig("webpack.config.js"), …
```
> refactor: replaces cruise function with signature from futureCruise BREAKING

- .dependency-cruiser.json
- configs/.dependency-cruiser-show-metrics-config.mjs
- src/cache/cache.mjs
- src/cli/format-meta-info.mjs
- src/cli/init-config/find-extensions.mjs
- src/extract/clear-caches.mjs
- src/extract/gather-initial-sources.mjs
- src/extract/get-dependencies.mjs
- src/extract/parse/to-javascript-ast.mjs
- src/extract/parse/to-typescript-ast.mjs
- src/extract/resolve/determine-dependency-types.mjs
- src/extract/resolve/external-module-helpers.mjs
- src/extract/resolve/get-manifest.mjs
- src/extract/resolve/index.mjs
- src/extract/resolve/module-classifiers.mjs
- src/extract/resolve/resolve-amd.mjs
- src/extract/resolve/resolve-cjs.mjs
- src/extract/resolve/resolve-helpers.mjs
- src/extract/transpile/index.mjs
- src/extract/transpile/meta.mjs
- src/main/index.mjs
- src/main/resolve-options/normalize.mjs
- test/extract/resolve/resolve-helpers.spec.mjs
- test/extract/transpile/meta.spec.mjs
- removes the default export from extract/ meta
(I think its usage is clearer now)
> refactor(extract): removes default export from meta

- src/cache/cache.mjs
- src/cache/content-strategy.mjs
- src/cache/find-content-changes.mjs
- src/cache/helpers.mjs
- src/cache/metadata-strategy.mjs
- src/cache/options-compatible.mjs
- test/cache/content-strategy.spec.mjs
- test/cache/find-content-changes.spec.mjs
- test/cache/metadata-strategy.spec.mjs
- test/cache/options-compatible.spec.mjs
- converts the cache modules to esm
See other PR's regarding esm conversion
> refactor(cache): converts to esm

- src/cli/init-config/build-config.mjs
- src/cli/init-config/index.mjs
- src/cli/init-config/utl.cjs
- src/cli/init-config/utl.mjs
- src/cli/init-config/write-run-scripts-to-manifest.mjs
- test/cli/init-config/create-config.spec.mjs
- test/cli/init-config/utl.spec.mjs
- converts stuff that calls (mandatorily commonjs) handlebars code to esm as well
> refactor(cli): converts hbs calling code in init-config to esm

- src/cache/helpers.mjs
- src/cli/init-config/validators.mjs
- src/cli/normalize-cli-options.mjs
- src/config-utl/extract-depcruise-config/index.mjs
- src/config-utl/extract-depcruise-config/merge-configs.mjs
- src/config-utl/extract-ts-config.mjs
- src/enrich/derive/folders/aggregate-to-folders.mjs
- src/enrich/derive/folders/utl.mjs
- src/extract/gather-initial-sources.mjs
- src/extract/get-dependencies.mjs
- src/main/helpers.mjs
- src/main/resolve-options/normalize.mjs
- test/config-utl/extract-depcruise-config/index.spec.mjs
- test/config-utl/make-absolute.spec.mjs
- test/extract/resolve/get-manifest.spec.mjs
- test/extract/transpile/typescript-wrap.spec.mjs
- tools/regenerate-main-fixtures.utl.mjs
- tools/regenerate-report-fixtures.utl.mjs
- uses qualified imports for imports from node native modules
- replaces lodash.get statements with optional chaining wherever that improved readability
consistency (hmm - would there be an eslint rule for this? with a fixert?)
> refactor: uses qualified imports for imports from node native modules

- doc/api.md
- doc/faq.md
- doc/options-reference.md
- src/cli/index.mjs
- src/config-utl/extract-babel-config.mjs
- src/config-utl/extract-webpack-resolve-config.mjs
- test/config-utl/extract-webpack-resolve-config-native.spec.mjs
- test/config-utl/extract-webpack-resolve-config-non-native.spec.mjs
- uses `import` instead of require for webpack configurations that look like they can be loaded natively.
- still uses the `require` hack with rechoir/ interpret for configurations that look different.
This makes the config util that loads webpack configurations asynchronous which is 🚨 BREAKING.
- to remain consistent with the formats we support for babel and dependency-cruiser itself.
- because it's possible now.
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/ …
> feature(config-utl): enables webpack configurations in ESM format BREAKING

- src/report/csv.mjs
- src/report/error.mjs
- src/report/text.mjs
- test/cli/asserthelpers.utl.mjs
- test/report/csv/csv.spec.mjs
- test/report/error/error-long.spec.mjs
- test/report/error/error.spec.mjs
- test/report/text/text.spec.mjs
- uses os.EOL in stead of hard coded `\n` so it's emitting the 'correct' eol on mswindows as wel
- 🏕️ in the csv reporter replaces reduce with a map + join for readability
> refactor(report): makes csv, error and text reporters less OS dependent

- README.md
- adds notes on how to run commands with dependency-cruiser v12 
Fixes #798 
> doc: makes readme backwards compatible

- .dependency-cruiser.json
- src/cli/format.mjs
- src/cli/index.mjs
- src/config-utl/extract-babel-config.mjs
- src/config-utl/extract-depcruise-config/read-config.mjs
- src/config-utl/extract-webpack-resolve-config.mjs
- src/main/cruise.mjs
- src/main/format.mjs
- src/main/index.mjs
- src/main/resolve-options/normalize.mjs
- test/main/main.cruise-reporterless.spec.mjs
- test/main/main.cruise.cache.spec.mjs
- test/main/main.cruise.dynamic-imports.spec.mjs
- test/main/main.cruise.reachable-integration.spec.mjs
- test/main/main.cruise.spec.mjs
- test/main/main.cruise.ts-pre-compilation-deps.spec.mjs
- test/main/main.cruise.type-only-imports.spec.mjs
- test/main/main.cruise.type-only-module-references.spec.mjs
- test/main/main.format.spec.mjs
- in 'main' splits off cruise and format in their own modules
- in the new 'cruise' module parallelizes dynamic imports of everything that can be optionally imported
- in the new 'cruise' module dynamically load _everything_ that can be optionally imported (in stead of just the perceived 'biggest wins')
- the split improves legibility/ maintainability
- the rest improves performance (normal runs without cache it doesn't make much difference;  cached, and when it can served directly from cache ~60ms)
```
$ hyperfine --warmup 3 --runs 30 "bin/dependency-cruise.mjs src bin test configs types tools --ignore-known --cache node_modules/.cache/dependency-cruiser/load-cached --no-progress"
Benchmark 1: bin/dependency-cruise.mjs src bin test configs types tools --ignore-known --cache …
```
> perf(main): splits off cruise & format in their own modules

- .dependency-cruiser.json
- configs/.dependency-cruiser-show-metrics-config.mjs
- src/main/format.mjs
- src/report/dot/default-theme.mjs
- By default, shows dynamic dependencies dashed lines in all dot reporters
For many applications dynamic imports behave differently from regular imports i.e. splitting code (bundlers like web pack, rollup, esbuild), deferred loading (nodejs). Having this available in the dot reporters has proved to be very useful, so it only makes sense to have it in by default (together with the existing alternate notations for type only, npm and circular dependencies). …
> feature(report): in dot reporters, by default makes dynamic dependencies dashed lines

- .dependency-cruiser.json
- doc/cli.md
- src/report/index.mjs
- src/report/null.mjs
- test/report/null/null.spec.mjs
- adds a reporter that reports nothing, only returns an exit code
Turns out to be useful during development 
> feature(report): adds a 'null' reporter

- src/enrich/summarize/summarize-options.mjs
- test/cli/__fixtures__/dynamic-import-nok.json
- test/cli/__fixtures__/dynamic-import-ok.json
- test/cli/__fixtures__/typescript-path-resolution.json
- test/main/__fixtures__/ts-no-precomp-cjs.json
- test/main/__fixtures__/ts-no-precomp-es.json
- test/main/__fixtures__/ts-precomp-cjs.json
- test/main/__fixtures__/ts-precomp-es.json
- types/cruise-result.d.ts
- types/options.d.ts
- adds tsconfig to the optionsUsed
- it's more complete & truthful that way
- we'll need it when we expand the cache feature to do incremental updates
- adds tsConfig, babelConfig, webpackConfig to the IConfiguration type
so if you have type checking on your .dependency-cruiser.js (or use the API) these don't get flagged anymore
Fixes #653
> fix(enrich): adds used tsconfig to options used + adds it to IConfiguration type

- package.json
- types/extract-ts-config.d.ts
This PR solves a small issue in 13.x, where types are missing when using the new `"exports"`.
The error from TypeScript was:
```
Could not find a declaration file for module 'dependency-cruiser'. '[...]/node_modules/dependency-cruiser/src/main/index.mjs' implicitly has an 'any' type.
There are types at '[...]/node_modules/dependency-cruiser/types/dependency-cruiser.d.ts', but this result could not be resolved when respecting package.json "exports". The 'dependency-cruiser' library may need to update its package.json or typings.ts (7016)
```
This PR also adds types for the `extract-ts-config` file, which we use and was previously untyped.
This solves a bug, as outlined above.
I've tested this locally against a project using dependency cruiser.
**Before (13.x)**
**After (13.x with …
> fix(types): add root and `extract-ts-config` types

- src/main/resolve-options/normalize.mjs
- test/main/resolve-options/normalize.spec.mjs
1. still load the tsconfig-paths-webpack-plugin when the baseUrl isn't defined and pass it `./` for baseUrl as a default path in those cases
1. when the baseUrl _is_ defined pass `undefined` as baseUrl to tsconfig-paths-webpack-plugin, so the plugin will read the baseUrl from 
Provides a workaround for https://github.com/dividab/tsconfig-paths-webpack-plugin/issues/99; fixes #818
When https://github.com/dividab/tsconfig-paths-webpack-plugin/pull/105 lands the second part of this PR should be reverted to keep the code as simple as possible
- The …
> fix(main): still load tsconfig-paths-webpack-plugin when baseUrl misses from tsconfig

- src/extract/resolve/resolve-amd.mjs
- src/extract/resolve/resolve-cjs.mjs
- test/extract/resolve/index.general.spec.mjs
- ensures `node:test` is detected as a core module
Currently `node:test` dependencies are classified as unable to resolve. This is because `node:test` or `test` are not listed as `builtinModules` in node's `module` module. From the discussion on https://github.com/nodejs/node/issues/42785 I understand this is never going to happen either. Alternative is to use `module`'s `isBuiltin()` function, but that is not available in the lowest version of nodejs dependency-cruiser supports (16.14), so we have to work around that.
Additionally the `node:test` module can _only_ be required via the `node:` protocol (`const { test} = require('test')`/ `import { test } from 'test'` don't work). This means that with the current the way we split the protocol from the module name, using `isBuiltin` won't …
> fix(extract): also detects node:test as a core module

- doc/faq.md
- src/cli/init-config/build-config.mjs
- src/schema/configuration.schema.json
- src/schema/cruise-result.schema.json
- test/cli/__fixtures__/init-config/no-config-files-exist/oeleboele.cjs
- test/cli/__fixtures__/init-config/no-config-files-exist/oeleboele.js
- tools/schema/options.mjs
- types/options.d.ts
First off, I just want to say thanks very much for producing and maintaining this tool. I've been amazed at how fast/powerful it is, and the thorough documentation in config and READMEs has been super helpful! Thank you! ❤️ 🙇 
The FAQs mention that if types from a package cannot be resolved then the user should configure `mainFields` to include the keys that the package is using in its `package.json` file.
The generated config and documentation suggest using `main` and `types` as `mainFields`. However, [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) notes that:
> ... the "typings" field is synonymous with types, and could be used as well.
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
Rather than …
> Suggest `typings` as a `mainFields` wherever `types` is suggested

- src/report/error-html/index.mjs
- test/report/error-html/error-html.spec.mjs
- corrects the code that puts 'ignored' on rows of ignored violations to actually do that
Fixes bug mentioned in the title
> fix(report/err-html): makes show/hide ignored violations work again

- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/cli/index.mjs
- src/extract/gather-initial-sources.mjs
- test/extract/gather-initial-sources.spec.mjs
- test/main/main.cruise.cache.spec.mjs
- replaces `glob` with `picomatch`
This PR makes use of the fact that dependency-cruiser just dropped support for node 16 and 19, using nodejs >=18.17 feature - `readdirSync`'s `recursive` option.
See #839; reduces number of external dependencies, which reduces both security risks, maintenance effort and install size.
Not the goal of this exercise, but it also reduces the start-up time and the execution speed of the gatherInitialSources step:
|test|glob|picomatch|
|--    |-- |--
| `npm test -f "[I] extract/gatherInitialSources"` as measured by mocha | 70ms | 43ms
| gatherInitialSources step in `node ./bin/dependency-cruise.mjs  --no-cache -Tnull  'src/**'` ('real' time)| 39ms  | 24ms
| gatherInitialSources step in `node ./bin/dependency-cruise.mjs  --no-cache -Tnull  src` ('real' time)| …
> refactor: replaces 'glob' with 'picomatch'

- src/cli/init-config/build-config.mjs
- src/cli/init-config/get-user-input.mjs
- src/cli/init-config/index.mjs
- src/cli/init-config/types.d.ts
- test/cli/init-config/build-config.spec.mjs
- If the current package.json contains a `type` attribute with the value `module` add `module` to the list of mainFields enhanced resolve should use in its (external) module resolution.
- Makes the default mainFields `['main', 'types', 'typings']` over just `['main']` (or a comment) as it's _always_ useful in TypeScript project (which is likely in the majority of all JavaScript projects out there) and doesn't hurt in other contexts.
Additionally, a separate commit, outside this PR, documents the working of the mainFields attribute for ESM contexts (b92b79bd)
#843 
- The contribution will be subject to [The MIT license](https://github.com/sverweij/dependency-cruiser/blob/main/LICENSE), and I'm OK …
> feat(init): adds 'module' field to enhancedResolve mainFields when current module is type:module

- bin/depcruise-baseline.mjs
- bin/depcruise-fmt.mjs
- bin/dependency-cruise.mjs
- src/cli/assert-node-environment-suitable.mjs
- src/main/cruise.mjs
- src/main/format.mjs
- src/main/options/assert-validity.mjs
- src/main/rule-set/assert-validity.mjs
- test/cli/validate-node-environment.spec.mjs
- test/main/options/assert-validity.spec.mjs
- test/main/rule-set/assert-validity.spec.mjs
- test/validate/parse-ruleset.utl.mjs
* in the cli renames assertion that checks whether the node environment is suitable
* in the main 'option' check renames functions that assert whether the options are valid
* in the main 'rule-set' renames functions that assert whether the rule set is valid
A lot of the assertions dependency-cruiser makes before starting were called 'validate' - which is not as clear/ descriptive of the actual functionality of the functions as 'assert' is. Renaming  …
> refactor: renames functions that assert things so they reflect that

- src/cli/index.mjs
- src/cli/normalize-cli-options.mjs
- src/config-utl/extract-depcruise-config/index.mjs
- src/enrich/derive/reachable.mjs
- src/enrich/summarize/add-rule-set-used.mjs
- src/extract/resolve/merge-manifests.mjs
- src/graph-utl/consolidate-module-dependencies.mjs
- src/graph-utl/consolidate-modules.mjs
- src/graph-utl/filter-bank.mjs
- src/main/helpers.mjs
- src/main/options/normalize.mjs
- src/main/rule-set/normalize.mjs
- src/report/anon/index.mjs
- src/report/dot/theming.mjs
- test/main/norm-base-directory.utl.mjs
- test/report/anon/anonymize.spec.mjs
- replaces lodash/cloneDeep with native structuredClone
- replaces lodash/clone with native structuredClone
Ongoing effort to reduce # of 3rd party dependencies (including that of lodash)
> refactor: replaces lodash's clone & cloneDeep with native structuredClone

- src/extract/resolve/index.mjs
- src/extract/resolve/resolve.mjs
- src/main/resolve-options/normalize.mjs
- test/main/resolve-options/normalize.spec.mjs
- removes most preserveSymlink processing in favor of passing the preserveSymlink option  to enhanced-resolve (which does this out of the box).
- unwraps the swallow-tail in the resolve index & refactors the yarn/ berry `resolveVirtual` things
- It's now properly reflected EHR's `symlinks` === `!preserveSymlink`
- Simplifies our code
- By moving it to enhanced-resolve the properly resolved module name is available earlier in the process. This will make our live easier when we'd ever want to use that e.g. for workspaces (which are nothing but symlinks from node_modules to local folders).
- The contribution will be subject to [The MIT license](https://github.com/sverweij/dependency-cruiser/blob/main/ …
> refactor(resolve): hands over preserveSymlink processing to EHR

- src/report/dot/default-theme.mjs
- test/report/dot/theming.spec.mjs
- _only_ color modules & dependencies in one of the severity level colors when there's a severity set on the associated rule
The default `dot` configuration built into dependency-cruiser made that things that were invalid, but for which the rule was _ignored_ showed up with a red color. This is obviously not helpful (why otherwise ignore the rule).
> feat(reporter/dot): only considers rule severity for coloring invalid modules/ dependencies

- src/cli/init-config/config-template.mjs
- makes initial regular expressions more specific
fixes #871 
The regexes generated previously matched more than they should have. 
> fix(init): makes initial regular expressions more specific

- .dependency-cruiser.json
- src/cli/init-config/config-template.mjs
- types/extract-ts-config.d.ts
- adds an exception to the `not-to-dev-dep` for type-only dependencies to ones in `@types` folders (which are _pretty_ likely to be type only as well, even when not explicitly imported as such)
- does the same for dependency-cruiser's own configuration
Implements the second suggestion from #873 
> feat(init): adds exception to not-to-dev-dep for type-only dependencies

- src/extract/ast-extractors/extract-typescript-deps.mjs
- test/extract/ast-extractors/extract-typescript-type-imports-and-exports.spec.mjs
Detect dependencies extracted from TypeScript as `'type-only'` also when all of the inline imports/re-exports are qualified as `type`.
[TypeScript 4.5 added inline type imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names). `dependency-cruiser` has support for `'type-only'` in `dependencyTypesNot`, but this only works when using type import statements, and not when regular import statements have all their inline imports qualified as `type`.
This can be fixed by moving the individual type imports to a separate type import statement, but this is cumbersome for some of us since using [ESLint's consistent-type-imports with `fixStyle: 'inline-type-imports'`](https://github.com/typescript-eslint/typescript-eslint/blob/main/package …
> feat(extract): detect 'type-only' with inline imports/exports

- doc/options-reference.md
- src/report/dot/theming.mjs
- test/report/dot/theming.spec.mjs
- adds ability to match arrays for conditional coloring on the dot reporter's theming
So it's possible to add formatting based on array like properties (like `dependencyTypes`) and to have a convenient way to match against multiple criteria at the same time.
E.g. to color based on types of aliased dependency types like this:
(from the reproduction example for #863 on https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/863)
... you can use this configuration that uses most features enabled by this PR:
```javascript
/** @type {import('dependency-cruiser').IConfiguration} */
module.exports = {
options: {
doNotFollow: { path: "node_modules" },
moduleSystems: ["es6", "cjs"],
tsPreCompilationDeps: true,
combinedDependencies: true,
tsConfig: { fileName: "tsconfig.json" }, …
```
> feat(report/dot): adds ability to match arrays for conditional coloring

- src/extract/resolve/module-classifiers.mjs
- test/extract/resolve/module-classifiers.get-alias-types.spec.mjs
- fixes the bug described in the title
> fix(extract): prevents classifying core modules as aliased-tsconfig-base-url

- src/enrich/derive/circular.mjs
- src/enrich/derive/metrics/get-module-metrics.mjs
- src/graph-utl/indexed-module-graph.mjs
- test/graph-utl/__mocks__/cycle-input-graphs.mjs
- test/graph-utl/indexed-module-graph.spec.mjs
- normalizes name attribute on construction to simplify processing. Before you had to specify whether you'd use _resolved_ (for regular modules) or _name_ (for folders) when invoking any method that needed these (e.g. getCycle).
- refactors the getCycle attribute a bit so it emits the correct output for self-referencing modules
- makes some methods that were meant to be private really private
- renames some things to be a bit closer to default graph theory nomenclature …
> refactor(graph-utl): normalizes name attribute of dependencies on construction to simplify processing

- src/config-utl/extract-known-violations.mjs
- test/config-utl/__mocks__/known-violations/known-violations-with-cycles-in-new-format.json
- test/config-utl/__mocks__/known-violations/known-violations-with-cycles-in-old-format.json
- test/config-utl/extract-known-violations.spec.mjs
- makes possibly old format known violations forward compatible directly after reading
... to prevent users from bumping into inexplicable errors. See the comment in 
extract-known-violations.mjs for details.
> feat(config-utl): makes possibly old format known violations forward compatible

- doc/rules-reference.md
- src/extract/helpers.mjs
- src/report/dot/default-theme.mjs
- test/extract/get-dependencies.odds-and-ends.spec.mjs
- test/extract/helpers-detect-pre-compilation-ness.spec.mjs
- tools/schema/dependency-type.mjs
- types/shared-types.d.mts
- when a dependency classifies as `preCompilationOnly: true` also add `"pre-compilation-only"` to the `dependencyTypes` array for that dependency
- in the default theme of the `dot` reporter 
- use the `dependencyTypes` array instead of the loose boolean attributes
- also use the 'thin line' representation for things we can with high likelihood
classify as pre-compilation only (type-only, type-import, tsd type import)
Consistency with other similar (derived or not) dependency types …
> feat(extract): adds "pre-compilation-only" to the dependencyTypes as well, when detected

- doc/options-reference.md
This fixes a small typo in the dependency required to run with `parser: "swc"`
> docs: fix typo in swc dependency

- package-lock.json
- package.json
- src/cache/metadata-strategy.mjs
- migrates to watskeburt 3
Keep up with  the  times
> chore(cache): migrates to watskeburt 3

- .dependency-cruiser.json
- configs/rules/no-deprecated-core.cjs
- configs/rules/no-orphans.cjs
- src/cli/init-config/config-template.mjs
- modifications to the rules & configuration `--init` generates by default when setting up dependency-cruiser in a new repository:
- adds .jsx, .tsx, .mts and .cts extensions to some fo
- uses _non_-capturing groups in regexes that don't need groups to be capturing
- remove regex grouping where it isn't needed (either to group expressions or to make a regex more readable)
- also consider `apps` and `libs` as folders to collapse to for the `archi` reporter config in addition to `app` and `lib` (and other generic folder names like `src` etc).
- apply some of these to dependency-cruiser own .dependency-cruiser.json
- fixes #916 
- making regex groupings non-capturing where they aren't needed for capturing things should make them faster to process (not measured as I don't expect much of an …
> fix(init): adds often used suffixes to some of the initial rules

- src/extract/resolve/module-classifiers.mjs
- test/extract/resolve/module-classifiers.get-alias-types.spec.mjs
- ignores 'workspaces' field when it isn't an array _and_  it doesn't contain a yarn1 workspaces.packages field
- also classifies dependencies resolving via yarn1 workspaces.packages fields  as _aliased_, _aliased-workspace_
fixes #919 
Note: a version with this fix has been published as `dependency-cruiser@16.2.4-beta-1` - once the PR is merged it'll be part of dependency-cruiser@16.2.4.
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/main/.github/CONTRIBUTIN …
> fix(resolve): makes dependency classifier handle more flavours of the 'workspaces' type alias field

- package-lock.json
- package.json
- src/cache/helpers.mjs
- src/extract/parse/to-javascript-ast.mjs
- src/extract/parse/to-swc-ast.mjs
- src/extract/parse/to-typescript-ast.mjs
- src/extract/resolve/external-module-helpers.mjs
- src/extract/resolve/get-manifest.mjs
- src/extract/resolve/resolve-amd.mjs
- src/report/anon/anonymize-path-element.mjs
- replaces `lodash/memoize` with `memoize`
We should slowly be starting to replace lodash functions everywhere as lodash isn't really maintained anymore. Additionally `lodash/memoize` isn't the fastest memoization function around, it looks like. 
The chosen alternative (`memoize`, formerly known as `mem`) isn't the fastest either, but
- seems to be reliably maintained
- has recent updates
- is decently fast (see benchmarks below)
- is not too large (& doesn't ship unnecessary stuff to npm like tests, sources, bundles, benchmarks, ...)
- performs decently and reliably
- takes a custom resolver function (which it calls 'cacheKey'), which is a thing we regrettably need.
Other candidates either have fallen out of maintenance (e.g. 10y without updates, ...), or miss features we need.
<details> …
> refactor: replaces lodash/memoize with memoize

- .c8rc.json
- src/cli/init-config/environment-helpers.mjs
- src/cli/init-config/normalize-init-options.mjs
- src/cli/normalize-cli-options.mjs
- src/config-utl/extract-depcruise-config/index.mjs
- src/enrich/derive/reachable.mjs
- src/enrich/summarize/summarize-folders.mjs
- src/enrich/summarize/summarize-modules.mjs
- src/enrich/summarize/summarize-options.mjs
- src/extract/index.mjs
- src/extract/resolve/determine-dependency-types.mjs
- src/extract/resolve/external-module-helpers.mjs
- src/graph-utl/add-focus.mjs
- src/graph-utl/rule-set.mjs
- src/main/cruise.mjs
- src/main/helpers.mjs
- src/main/options/assert-validity.mjs
- src/main/options/normalize.mjs
- src/main/report-wrap.mjs
- src/main/rule-set/assert-validity.mjs
- src/main/rule-set/normalize.mjs
- src/report/anon/index.mjs
- src/report/dot/index.mjs
- src/report/dot/module-utl.mjs
- src/report/error-html/utl.mjs
- src/report/plugins.mjs
- src/validate/index.mjs
- src/validate/match-module-rule.mjs
- src/validate/matchers.mjs
- src/validate/rule-classifiers.mjs
- replaces lodash/has & lodash/get with native options where possible
because it now often _is_ easily possible with native options
> refactor: replaces lodash/has & lodash/get with native options where possible

- src/graph-utl/rule-set.mjs
- test/graph-utl/rule-set.spec.mjs
- lets findRuleByName also search in 'required' rules
fixes #930 
With this rule added to dependency-cruiser's own config
```javascript
// ...
"required": [
{
"name": "something-required",
"comment": "Foo bar baz quux garply waldo fred plugh xyzzy thud",
"severity": "warn",
"module": {
"path": "^src/meta.cjs$"
},
"to": {
"path": "^test/kannie"
}
}
],
// ...
```
... `npx depcruise --progress -T err-long` shows this:
```
warn something-required: src/meta.cjs
Foo bar baz quux garply waldo fred plugh xyzzy thud
✘ 1 dependency violations (0 errors, 1 warnings). 545 modules, 1325 dependencies cruised.
⚠ 7 known violations ignored. Run with --no-ignore-known to see them.
```
- The contribution will be …
> fix(graph-utl): lets findRuleByName also search in 'required' rules

- .dependency-cruiser.json
- doc/api.md
- package.json
- src/config-utl/extract-depcruise-config/index.mjs
- src/config-utl/extract-depcruise-config/read-config.mjs
- src/config-utl/extract-depcruise-options.mjs
- test/config-utl/__mocks__/depcruiseconfig/empty.mjs
- test/config-utl/__mocks__/depcruiseconfig/rules.sub-not-allowed-error-with-options.json
- test/config-utl/__mocks__/depcruiseconfig/rules.sub-not-allowed-error.json
- test/config-utl/extract-depcruise-options.spec.mjs
- types/config-utl/extract-depcruise-config.d.mts
- types/config-utl/extract-depcruise-options.d.mts
- types/dependency-cruiser.d.mts
- adds utility that extracts dependency-cruiser options from a dependency-cruiser config, and that returns an `ICruiseOptions` one can use as input parameter for the `cruise` function. This function also sets the `validate` attribute to `true` if there's a rule set in the config (and to `false` otherwise), so there's no need to do that anymore either.
- corrects the documented method signature of `extractDepcruiseConfig` to what it really returns (an `IConfiguration`)
- updates the docs/api.md documentation so all examples (1) run as intended (2) reflect current situation of the API.
fixes #932 
`extractDepcruiseConfig` returns an `IConfiguration` object while the cruise function needs an `ICruiseOptions`. Changing the signature of `extractDepcruiseConfig` would constitute a breaking …
> fix(config-util): adds utility that extracts dependency-cruiser options from a dependency-cruiser config

- .dependency-cruiser-known-violations.json
- .dependency-cruiser.json
- package-lock.json
- package.json
- src/config-utl/extract-babel-config.mjs
- src/config-utl/extract-ts-config.mjs
- src/extract/swc/dependency-visitor.mjs
- src/extract/swc/parse.mjs
- src/extract/transpile/babel-wrap.mjs
- src/extract/transpile/coffeescript-wrap.mjs
- src/extract/transpile/livescript-wrap.mjs
- src/extract/transpile/svelte-wrap.mjs
- src/extract/transpile/typescript-wrap.mjs
- src/extract/transpile/vue-template-wrap.cjs
- src/extract/tsc/extract-typescript-deps.mjs
- src/extract/tsc/parse.mjs
- src/utl/extract-root-module-name.cjs
- src/utl/try-import.mjs
- src/utl/try-require.cjs
- test/extract/transpile/vue3-template-wrap.spec.mjs
- test/utl/extract-root-module-name.spec.cjs
- test/utl/node_modules/beta/index.js
- test/utl/node_modules/beta/package.json
- test/utl/node_modules/no-default-export/main.mjs
- test/utl/node_modules/no-default-export/package.json
- test/utl/node_modules/rc/index.js
- test/utl/node_modules/rc/package.json
- test/utl/try-import.spec.mjs
- test/utl/try-require.spec.cjs
- pulls in the try-import and try-require functions from semver-try-require
- removes the semver-try-require dependency
semver-try-require is only used by dependency-cruiser. Although it _might_ have been used by other packages it isn't. Maintaining semver-try-require as a separate package introduces overhead that isn't warranted => should simplify releasing dependency-cruiser.
As a separate action semver-try-require will be deprecated. …
> refactor: pulls semver-try-require functionality in & removes the dependency

- package-lock.json
- package.json
- src/utl/wrap-and-indent.mjs
- removes 3rd party dependency 'indent-string'
- replaces it with the simple string replace it ultimately comes down to (regex shamelessly copied from the indent-string package).
Less dependencies => less maintenance overhead. Moreover, the part of  indent-string we actually use is _so_ trivial it's simpler to pull it in.
> refactor: removes 3rd party dependency 'indent-string'

- src/extract/transpile/vue-template-wrap.cjs
- test/extract/transpile/vue-template-wrap.spec.mjs
Currently the vue2 template compiler only extracts content from the `script` section of single file components. [Script setup SFCs are supported since version 2.17](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#270-2022-07-01). This MR updates the implementation analogous to the vue 3 `@vue/compiler-sfc` to extract content from `<setup script>` components in case they exist
Without this change Vue 2 components using `<script setup>` appear empty to dependency cruiser leading to missing imports.
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/mai …
> fix(extract/transpile): transpile script setup with vue 2

- src/enrich/summarize/summarize-modules.mjs
- src/extract/transpile/vue-template-wrap.cjs
- src/graph-utl/consolidate-module-dependencies.mjs
- src/graph-utl/consolidate-modules.mjs
- src/main/options/assert-validity.mjs
- src/main/resolve-options/normalize.mjs
- test/main/options/assert-validity.spec.mjs
- replaces lodash' flattenDeep, isEmpty, reject, omit, merge with native alternatives
Part of a series of PR's to phase out lodash (which is not maintained anymore) as a production dependency.
> refactor: replaces lodash' flattenDeep, isEmpty, reject, omit, merge with native alternatives

- package-lock.json
- package.json
- src/report/error.mjs
- src/utl/wrap-and-indent.mjs
- removes 3rd party dependency 'wrap-ansi'
Reduces the number of 3rd party dependencies by 7, which is good for download size & performance and reduces potential vulnerabilities and maintenance burden.
We _do_ wrap with ansi-codes, but if we apply the ansi codes _after_ wrapping, we don't need the specialised `wrap-ansi` package anymore and can do with a simple hand-rolled function for wrapping, which is what this package implements (the function is _ugly_, and might not cover all edge cases but it works well enough for our use case).
From [npmgraph](https://npmgraph.js.org/?q=wrap-ansi):
- The contribution will be subject to [The MIT license](https://github.com/sverweij/dependency-cruiser/blob/mai …
> refactor: removes 3rd party dependency 'wrap-ansi'

- src/extract/resolve/module-classifiers.mjs
- test/extract/resolve/module-classifiers.get-alias-types.spec.mjs
- ignore entries in 'workspaces' arrays that aren't strings, instead of throwing an exception
Yarn workspaces is an array of strings according to [its documentation](https://yarnpkg.com/configuration/manifest#workspaces). Apparently is possible (and accepted?) to have other types than strings as well. Not sure whether that is _valid_, but at least it's happening in the field, witnessing #947, so we deal with it.
Addresses the error mentioned in #947 (and likely fixes it) …
> fix(extract): ignore entries in 'workspaces' arrays that aren't strings (instead of throwing)

- doc/cli.md
- src/cli/format-meta-info.mjs
- src/extract/swc/parse.mjs
- src/extract/transpile/babel-wrap.mjs
- src/extract/transpile/coffeescript-wrap.mjs
- src/extract/transpile/javascript-wrap.mjs
- src/extract/transpile/livescript-wrap.mjs
- src/extract/transpile/meta.mjs
- src/extract/transpile/svelte-wrap.mjs
- src/extract/transpile/typescript-wrap.mjs
- src/extract/transpile/vue-template-wrap.cjs
- test/extract/transpile/meta.spec.mjs
- enriches the --info output with info relevant for troubleshooting environment issues:
- versions of transpilers _found_
- current version of dependency-cruiser
- supported node versions, found node version
- found os
Makes it easier to debug issues in the setup. E.g. seeing that dependency-cruiser finds typescript@4 is used instead of an expected typescript@5 already gives clues to 
```
dependency-cruiser@16.4.2
node version supported : ^18.17||>=20
node version found     : v22.8.0
os version found       : x64 darwin@21.6.0
If you need a supported, but not enabled transpiler ('x' below), just install
it in the same folder dependency-cruiser is installed. E.g. 'npm i livescript'
will enable livescript support if it's installed in your project folder.
✔ transpiler             versions …
```
> feat(cli): expands the info displayed in --info

- .dependency-cruiser-known-violations.json
- src/cli/init-config/build-config.mjs
- src/cli/init-config/config-template.mjs
- src/cli/init-config/get-user-input.mjs
- src/cli/init-config/index.mjs
- src/cli/init-config/types.d.ts
- src/cli/init-config/write-run-scripts-to-manifest.mjs
- adds question to enable detection of jsdoc imports to the --init  command
Improves discoverability 
> feat(init): adds question to enable detection of jsdoc imports

- src/extract/helpers.mjs
- src/extract/resolve/is-built-in.mjs
- test/extract/helpers-extract-module-attributes.spec.mjs
- test/extract/resolve/index.general.spec.mjs
- test/extract/resolve/is-built-in.spec.mjs
- uses `modules.isBuiltin` instead of the `modules.builtinModules` array, so throwing in builtin modules wih protocol prefixes doesn't need any pre- or post processing anymore. We can do this since now all versions of node we support have the `modules.isBuiltin` method available.
- adds `bun:` to the list of protocols we recognize.
- leaves the protocol with the module name for builtins that are only available with the protocol in the name (e.g. node:test, node:sqlite, node:sea or bun:ffi).
- Makes it easier to support new builtin modules that follow the new trend of being protocol-prefixed only.
- Now out of the box supports recognizing node:sqlite, node:sea, node:test/reporters as core modules.
- Adds support for recognizing modules prototype-prefixed with `bun:` (which is relevant if …
> feat(extract): improves detection of protocol-only builtins (node & bun)

- doc/options-reference.md
- src/cli/init-config/build-config.mjs
- src/cli/init-config/config-template.mjs
- src/cli/init-config/environment-helpers.mjs
- src/cli/init-config/get-user-input.mjs
- src/cli/init-config/index.mjs
- src/cli/init-config/types.d.ts
- test/cli/init-config/build-config.spec.mjs
- test/cli/init-config/environment-helpers.spec.mjs
- adds an option to the init config to (1) detect whether bun is likely used (2) add the bun builtins in the config.
seems useful for those projects that use bun
> feat(cli): adds init option for bun

- .github/workflows/ci.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- src/cli/init-config/environment-helpers.mjs
- src/cli/normalize-cli-options.mjs
- src/cli/utl/assert-file-existence.mjs
- src/extract/resolve/resolve-amd.mjs
It does 2 things:
* imports R_OK via constants instead of direct import
* replaces 23 node with 24 in CI
R_OK was removed from fs in nodejs 24 https://github.com/nodejs/node/pull/49686
> fix: adds support for node v24

- bin/depcruise-baseline.mjs
- replaces commander with node:util/parseArgs (depcruise-baseline)
Less dependencies = better
> refactor(cli): replaces commander with node:util/parseArgs - depcruise-baseline

- .github/workflows/ci.yml
- doc/cli.md
- package-lock.json
- package.json
- src/meta.cjs
- test/cli/validate-node-environment.spec.mjs
- drops support for node 18, 21 and 23; sets the minimum required node version to 20.12, 
- updates the ci to reflect this
We follow the node.js release cycle (as slow as possible) -- node 18 and 21 are end of life since 2025-03-27 and 2024-04-10 (!) respectively and shouldn't be run in production anymore. Same goes for node 23. Moreover node 20 has been in production since 2023-03-18, node 22 since 2024-03-24, so most serious consumers will have migrated to one of these versions already - if they aren't on node 24, that is.
We've tried to keep this off as long as possible but some of our dependencies (like commander.js) dropped support for node 18 and we want to keep those up to date to keep dependency-cruiser secure. Moreover node.js 20+ has useful features that makes it possible to do …
> chore!: drops support for node 18, 21 and 23 BREAKING

- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/cli/format-meta-info.mjs
- src/cli/index.mjs
- src/cli/init-config/write-config.mjs
- src/cli/init-config/write-run-scripts-to-manifest.mjs
- src/cli/listeners/cli-feedback.mjs
- src/cli/listeners/performance-log/format-helpers.mjs
- src/report/error.mjs
- src/report/metrics.mjs
- src/report/text.mjs
- replaces picocolors with node:util/styleText
- as the first parameter of styleText use a _string_ in stead of an array as only with strings does NO_COLORS work in node 20 (it works fine in node 22 and 24) as well - see https://github.com/nodejs/node/issues/56717 for details
- ⛺ side-catch: removes Node.js 18 specific workarounds from the ci workflow.
Less dependencies === less worries
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/main/.github/CONTRIBUTING. …
> refactor!: replaces picocolors with node:util/styleText

- package-lock.json
- package.json
- src/report/teamcity.mjs
- test/report/teamcity/teamcity.spec.mjs
- replaces teamcity-service-messages with local functions
The teamcity-service-messages has been working great, without a hitch since the moment we started using it. It's not maintained anymore, however, that's not an issue either: _there's no need for maintenance and it's dependency-less. 
However, it _does_ remain a dependency, while the functionality we use of it is relatively straightforward. With dependencies there's always the risk some overactive go-getter finds a bogus CVE, or, potentially worse, the package owner gets hacked and all of a sudden there _is_ a risk because just installing it will run an llm-crypto-miner-scam-of-the-day on install.
It also makes dependency-cruiser's installed footprint slightly smaller.
AKA less dependencies === more happiness.
- My change doesn't …
> refactor(report): replaces teamcity-service-messages with local functions
