sverweij/dependency-cruiser

README.md
Just some small changes to make the readme more readable.
Fix them typos.
=> 📖  fix typos in readme

src/extract/transpile/typeScriptWrap.js, test/extract/transpile/fixtures/tsx.js, test/extract/transpile/fixtures/tsx.tsx, test/extract/transpile/tsxWrap.spec.js
With this, tsx gets translated to more valid javascript - so acorn has an easier job (and doesn't have to fall back to acorn_loose)
Unit tests
- ~~~New feature (non-breaking change which adds functionality)~~~
- ~~~Breaking change (fix or feature that would cause existing functionality to change)~~~
- ~~~My change requires a change to the documentation.~~~
- ~~~I have updated the documentation accordingly.~~~
=> Treat tsx a bit better

doc/api.md
the api doc lack the cruise ref;
detail on code
=> fix:lack cruise ref

doc/rules-reference.md
=> Fix syntax in JS configuration example

package.json, src/extract/gatherInitialSources.js, test/extract/gatherInitialSources.spec.js
=> bugfix(extract): tame exclude pattern matching

package.json, src/extract/resolve/compileResolveOptions.js, test/extract/resolve/fixtures/ts-config-with-path/src/common/wood/tree.ts, test/extract/resolve/fixtures/ts-config-with-path/src/typos/daddayaddaya.ts, test/extract/resolve/fixtures/ts-config-with-path/tsconfig.json, test/extract/resolve/index.spec.js
=> bugfix(resolve): swap out awesome-typescript-loader for tsconfig-paths-webpack-plugin

package.json, src/extract/resolve/index.js, src/extract/resolve/resolve.js, src/main/resolveOptions/normalize.js, test/extract/fixtures/amd.json, test/extract/fixtures/cjs.json, test/main/resolveOptions/normalize.spec.js
fixes #115 
- x ] The code I add will be subject to [The MIT license](../LICENSE), and I'm OK with that.
- ~~My change requires a change to the documentation.~~
- ~~I have updated the documentation accordingly.~~
=> bugfix(resolve): repairs preserve-symlink behavior to pre-4.14.0 behavior

.travis.yml, package.json
- Adds a simple load test - a first version that runs on dependency-cruiser itself and is (1) sort of repeatable and (2) is easy to set up and run.
- Runs it on the travis ci.
Next steps: run it on a fixed, relatively large, varied repo and/ or on several repos with various properties (js, ts, monorepo) and various parameters (i.e. with/ without tsPreCompilationDeps)
To get a gauge on what changes mean for how fast dependency-cruiser runs.
- It is a test :-)
=> feature(test): adds a simple load test

docs/dependency-cruiser-dependency-graph.html, src/extract/index.js, src/main/index.js, test/extract/index.spec.js
see title
better separation of concerns.
=> refactor(extract): keep the call to the reporter in main

src/report/csv/index.js, src/report/dot/common/folderify.js, src/report/dot/folderLevel/consolidateModuleDependencies.js, src/report/dot/folderLevel/consolidateModules.js, src/report/dot/folderLevel/index.js, src/report/dot/moduleLevel/index.js, src/report/err.js, src/report/html/index.js, src/report/json.js, src/utl/safe-regex.js
See title
gotta have some docs so it's more easier to maintain for others (like later selves).
=> bugfix(report): adds jsdoc

src/extract/index.js, test/cli/fixtures/cjs.dir.filtered.json, test/cli/fixtures/cjs.dir.json, test/cli/fixtures/cjs.file.json, test/cli/fixtures/dynamic-import-nok.json, test/cli/fixtures/dynamic-import-ok.json, test/cli/fixtures/multiple-in-one-go.json, test/cli/fixtures/typescript-path-resolution.json, test/cli/fixtures/webpack-config-alias-cruiser-config.json, test/cli/fixtures/webpack-config-alias.json, test/extract/fixtures/cache-busting-first-tree.json, test/extract/fixtures/cache-busting-second-tree.json, test/main/fixtures/dynamic-imports/es/output.json, test/main/fixtures/dynamic-imports/typescript/output-pre-compilation-deps.json, test/main/fixtures/dynamic-imports/typescript/output.json, test/main/fixtures/jsx-as-object.json, test/main/fixtures/jsx.json, test/main/fixtures/ts-no-precomp-cjs.json, test/main/fixtures/ts-no-precomp-es.json, test/main/fixtures/ts-precomp-cjs.json, test/main/fixtures/ts-precomp-es.json, test/main/fixtures/ts.json, test/main/fixtures/tsx.json
see above
cli & api call result should be as consistent as possible for the same input
-[x] automated testing
=> bugfix(extract): also put args in summary for api calls

src/main/ruleSet/config-schema.json, types/dependency-cruiser.d.ts
see title
Some of the latest features weren't up to date in the type definitions yet - this MR corrects that.
- ~~My change requires a change to the documentation.~~
- ~~I have updated the documentation accordingly.~~
=> bugfix(types): update type definitions

.dependency-cruiser.json, configs/rules/no-deprecated-core.js, configs/rules/no-duplicate-dependency-types.js
See title - tries to better explain the rules, so it's more clear why they're in place & what to do.
=> feature(rules): make the rule descriptions more contextually clear

src/report/err-html/err-html.template.hbs, src/report/err-html/err-html.template.js, test/report/err-html/err-html.spec.js
See title
- you still might want to know what checks were run, even though everything is hunky-dory
In collapsed state:
Expanded:
=> feature(report): also show all rules when there's no violation

doc/faq.md, doc/rules-reference.md
This wasn't in any of the the documentation yet - as identified in issue #160. This also describes the moduleSystems option a little better, with a small table explaining what each of the values mean.
With a spell checker
=> doc(faq|rules-reference): describe how to detect TypeScript tripple slash directives

package.json
- set up lint-staged, to make it easier to comply to coding & style standards
=> ci(*): set up lint-staged

test/cli/compileConfig/index.spec.js, test/cli/utl/validateFileExistence.spec.js, test/extract/resolve/isRelativeModuleName.spec.js, test/main/main.format.spec.js, test/main/options/validate.spec.js, test/main/ruleSet/validate.spec.js
see title
In some spots the tests checking for throws were not run in the simplest (and chai proscribed) way. This PR fixes that
=> refactor(test): correctly set up tests that check for things throwing

src/main/options/validate.js
=> bugfix(options): remove a stray typeof so the arrayness check executes

src/extract/derive/reachable/index.js, src/extract/derive/reachable/isReachable.js, src/validate/matchDependencyRule.js, src/validate/matchModuleRule.js
Renames things and simplifies them so it's easier to understand
=> refactor(extract|validate): small maintenance

.github/workflows/nodejs.yml
Seems a convenient addition to the CI's already in use. Might provide a good start to create a gh action that comments on PR's (i.e. with the dc err-html reporter?)
With this PR :-)
=> build(gh-actions): set up github actions CI

src/cli/tools/svg-in-html-snippets/header.snippet.html, utl/README.md
- small css tweak, so the html wrap also looks nice when the wrapped svg has dark background/ light foreground
- doc update
Green ci
=> bugfix(wrap-stream-in-html): css tweakery

src/cli/normalize-options.js
Previously it took a commander object that has a gazillion extra attributes that (1) are not relevant (2) might unintentionally trigger stuff downstream
- automated non-regression tests
=> refactor(cli): only pass on known cli options to downstream

README.md
=> fix "typo" in Readme about config file extension

.dependency-cruiser.json, doc/rules-reference.md, src/main/options/normalize.js, src/main/utl/normalize-re-properties.js, src/schema/configuration.schema.json, src/schema/cruise-result.schema.json, test/main/options/normalize.spec.js, tools/schema/reporter-options.mjs
Like #317 and #318, but for the _collapsePattern_ and all _filters_ in the _reporterOptions_
Consistency is the king of DX.
=> feature(*): allow reporter options to accept an array if RE's

doc/cli.md
Add an earlier mention of `depcruise-wrap-stream-in-html` to aid discoverability.
https://github.com/sverweij/dependency-cruiser/issues/343#issuecomment-670085693
N/A
=> doc(cli): mention wrap-stream-in-html earlier

src/enrich/clear-caches.js, src/enrich/derive/circular/get-cycle.js, src/enrich/derive/find-module-by-name.js, src/enrich/derive/reachable/get-path.js, src/enrich/index.js, test/enrich/derive/circular/get-cycle.spec.js, test/enrich/derive/reachable/get-path.spec.js, test/enrich/derive/reachable/index.spec.js
Makes finding cycles and reachables faster by using a cache (that is also shared between them)
Performance improvements will depend on the structure of the target repository - in real life we see improvements between 2x (on react) and 10x (on a 5000 module/ 21000 deps repo).
> For the curious: published as dependency-cruiser@9.11.0-beta-2
=> bugfix(enrich): improve performance of cycle and reachable detection

CHANGELOG.md
For now just points at the existing changelog on GitHub to improve discoverability of the actual changelog. Fixes #349 
- Green CI
=> doc(changelog): adds a CHANGELOG.md file

CODE_OF_CONDUCT.md
Updates the code of conduct to reflect the latest developments on the _contributor covenant_ - which this project was already following.
[ci skip]
=> doc: update code of conduct to contributor covenant 2.0

src/validate/match-dependency-rule.js, test/validate/fixtures/rules.please-duplicate-dep-types.json, test/validate/index.spec.js
=> bugfix(validate): also correctly validate situations where 'moreThanOneDependencyType' equals false

src/extract/transpile/babel-wrap.js
=> bugfix(babel): gives babel plugins a filename to work with

src/extract/resolve/local-npm-helpers.js
- limits limits the #times external manifests are retrieved by checking for locality
- improves performance quite a bit, even with rules that need the contents of the manifests, like licenses and deprecations (roughly 1.5s for dependency-cruiser for a regular cruise with the same parameters as in PR #412, roughly 3s on react (regular cruise of 1189 modules/ 3692 dependencies taking ~12s instead of 15s))
- I am ok with the stuff in [**CONTRIBUTING.md**](https://github.com/sverweij/dependency-cruiser/blob/develo …
=> perf(resolve): limits the #times external manifests are retrieved

src/report/plugins/index.js, test/report/plugins/index.get-external-plugin-reporter.spec.js
=> bugfix(plugin): make local plugins work better on on windows

src/extract/transpile/meta.js
=> bugfix(transpile): when swc is there also cite typescript as supported extensions

package.json, src/cli/init-config/write-run-scripts-to-manifest.js, test/cli/init-config/write-run-scripts-to-manifest.spec.mjs
See title. Seems practical to have in a default set of scripts
=> feature(init): adds a text and a 'focus' script to the experimental-scripts default config

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md
- Simplify wording in CONTRIBUTING.md
- Point to the issue creation dialog instead of to just 'new issue'
- Update twitter address to personal one
- Check & update links where necessary
- contributor covenant to 2.1
Make life easier (and more clear) for new contributors.
N/A
=> doc: updates contribution documentation

src/extract/get-dependencies.js, src/extract/parse/to-typescript-ast.js, test/extract/ast-extractors/extract-typescript.utl.mjs, test/extract/fixtures/vue.json, test/extract/fixtures/vue/javascriptThing.js, test/extract/fixtures/vue/sub/index.ts, test/extract/fixtures/vue/sub/kaching.ts, test/extract/fixtures/vue/vue.vue, test/extract/get-dependencies.spec.mjs
An attempt to make pipeline modifications proposed by @sverweij in linked issue.
Fixes #515
I did one unit test, but complexity of this project is little bit overwhelming and I don't know if I did this right enough. If not, I need some help and/or guidance to find places where I can add more tests.
Also I did some manual testing on my personal project (Vue + Typescript) where I need this feature.
Probably breaking for some users, because from now `.vue` files will report errors about pre compilation dependencies.
- The contribution is my own original …
=> feature: TypeScript support in Vue files (BREAKING CHANGE)

src/enrich/soften-known-violations.js, test/enrich/soften-known-violations.spec.mjs
... so they're ignored as known violation, which wasn't the case before
=> bugfix(known-violations): also soften self-cycling violations

Makefile
See title. Fixes an issue where `make` didn't always take, despite sources being changed.
=> chore(make): updates makefile to regard more sources

src/cli/format.js, types/dependency-cruiser.d.ts, types/options.d.ts
=> bugfix(types): adjusts 'format' type signature to use IFormatOptions

doc/options-reference.md
> Leave an [issue](https://github.com/sverweij/dependency-cruiser/issues/new/choose) with a
> do that, so we can have a conversation before you start. This will save you time!
=> fix: webpack typo

configs/plugins/mermaid-reporter-plugin.js, test/configs/plugins/mermaid-reporter-plugin/module-level/__mocks__/clusterless.mmd, test/configs/plugins/mermaid-reporter-plugin/module-level/__mocks__/contains-strings-to-be-escaped.json, test/configs/plugins/mermaid-reporter-plugin/module-level/__mocks__/contains-strings-to-be-escaped.mmd, test/configs/plugins/mermaid-reporter-plugin/module-level/__mocks__/dependency-cruiser-2019-01-14.mmd, test/configs/plugins/mermaid-reporter-plugin/module-level/__mocks__/do-not-follow-deps.mmd, test/configs/plugins/mermaid-reporter-plugin/module-level/__mocks__/es6-unresolvable-deps.mmd
=> fix(mermaid-plugin): replace some meta chars

src/graph-utl/add-focus.js
Reduces number of O(N) lookups by saving results (to a Set) & reduces a bit of complexity.
- code is easier to understand
- code is likely a bit faster
=> refactor(graph-utl): simplify add-focus implementation

src/extract/transpile/meta.d.ts, src/validate/index.d.ts, types/dependency-cruiser.d.ts
- see title
- will make it easier to use the API, both for TypeScript and JavaScript (in editors that support that).
=> bugfix(doc): corrects the exposed function type definitions to correct/ canonical ones

src/extract/transpile/meta.d.ts, src/validate/index.d.ts, types/dependency-cruiser.d.ts
This reverts commit f9887d127ee61e4e46502224f502e5470683938e.
fixes #644 
=> Revert "bugfix(doc): corrects the exposed function type definitions to correct/ canonical ones (#643)"

README.md
When I first came across your project and read the README, I got the impression it could only do two things: validate and show your grandma a nice graph. I was disappointed because I was hoping I could output the dependency graph in easily-parsable formats such as json. Later I was pleasantly surprised to see that you do support that!
This PR simply updates README to indicate that users may output dependency graphs in various formats, so future visitors will get a clearer picture of the scope and functionality.
See above
This is only a markdown change
NA
- The contribution will be subject to [The MIT license](https://github.com/sverweij/dependency-cruiser/blob/develop/LICENSE), and I'm OK with …
=> update readme to mention output formats

README.md
correcting a very minor typo :)
=> doc(readme): correct typo

.github/workflows/ci.yml, package.json, src/cache/cache.js, src/cache/revision-data.js
- corrects typing typos in the cache code
- tweaks the ci GHA to emit a diff graph on PR's (and a complete graph on regular commits)
=> refactor(cache): corrects typing typos

src/extract/transpile/svelte-preprocess.js, test/extract/transpile/svelte-preprocess.spec.mjs
- when pre-processing svelte templates ignore style tags with an attribute that indicates processing is necessary.
Published on npmjs as beta: dependency-cruiser-12.3.0-beta-1 (sha-sum: `9a483d3a723361375cf375097635d69f21c3cafe`).
- fixes #713
- also see the comment accompanying the code
=> feature(svelte): adds support for processing svelte templates with css pre-processors

package.json, src/meta.js, test/extract/transpile/meta.spec.mjs
=> fix: Add support for typescript v5

configs/.dependency-cruiser-show-metrics-config.mjs, src/main/files-and-dirs/normalize.mjs, src/main/helpers.mjs, src/main/index.mjs, src/main/options/defaults.mjs, src/main/options/normalize.mjs, src/main/options/validate.mjs, src/main/report-wrap.mjs, src/main/rule-set/normalize.mjs, src/main/rule-set/validate.mjs, test/enrich/derive/reachable.spec.mjs, test/extract/gather-initial-sources.spec.mjs, test/extract/get-dependencies.amd.spec.mjs, test/extract/get-dependencies.cjs.spec.mjs, test/extract/get-dependencies.odds-and-ends.spec.mjs, test/extract/index.cachebusting.spec.mjs, test/extract/index.donotfollow.spec.mjs, test/extract/index.exclude.spec.mjs, test/extract/index.maxdepth.spec.mjs, test/extract/resolve/external-module-helpers.spec.mjs, test/extract/run-get-dependencies-fixture.utl.mjs, test/main/files-and-dirs/normalize.spec.mjs, test/main/helpers.spec.mjs, test/main/options/normalize.cruise-options.spec.mjs, test/main/options/normalize.format-options.spec.mjs, test/main/options/validate.spec.mjs, test/main/resolve-options/normalize.spec.mjs, test/main/rule-set/normalize.spec.mjs, test/main/rule-set/validate.spec.mjs, test/validate/parse-ruleset.utl.mjs
> Leave an [issue](https://github.com/sverweij/dependency-cruiser/issues/new/choose) with a
> do that, so we can have a conversation before you start. This will save you time!
- converts everything in src/main to esm
See other PR's regarding esm
=> refactor(main): converts to esm

src/extract/ast-extractors/extract-typescript-deps.mjs
- makes detecting 'require' statements compatible with typescript >5.2.0 (while remaining backwards compatible)
Fixes this tsc warning, while staying backwards compatible:
```
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.
```
=> chore(extract): makes 'require' detection with typescript >5.2.0

doc/options-reference.md
The title or at least the on line code edit should say everything already.
=> Added missing ": true," in options-reference.md example.

src/extract/gather-initial-sources.mjs
- rewrites a reduce with a flatMap so it's easier to read & maintain
=> refactor(extract): rewrites gatherInitialSources reduce with flatMap

doc/options-reference.md
> Fixed document errors
Modify semicolons to commas
Found document errors while using it
=> doc: modify semicolons to commas

src/report/anon/random-string.mjs, test/cli/init-config/build-config.spec.mjs
- For randomness use node:crypto
less dependencies more better
=> refactor: for randomness use node:crypto

.github/codeql/codeql-config-actions.yml, .github/codeql/codeql-config-javascript.yml, .github/workflows/codeql-schedule.yml
- configures CodeQL for GitHub actions
It's available and might improve security, hence let's use it.
=> chore(ci): configures CodeQL for GitHub actions

.github/workflows/ci.yml, .github/workflows/semantic-pr-title.yml, .github/workflows/stale.yml
- updates softenKnownViolations to include reachability and (module level) instability validations
- adds unit tests to verify continued operation
Fixes code scanning alerts:
- https://github.com/sverweij/dependency-cruiser/security/code-scanning/39
- https://github.com/sverweij/dependency-cruiser/security/code-scanning/40
- https://github.com/sverweij/dependency-cruiser/security/code-scanning/41
- https://github.com/sverweij/dependency-cruiser/security/code-scanning/42 …
=> fix(ci): fixes code scanning alerts on github actions
